# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIs\CoMPlEx_hwConfig_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_hwConfig_dialog(object):
    def setupUi(self, hwConfig_dialog):
        hwConfig_dialog.setObjectName("hwConfig_dialog")
        hwConfig_dialog.resize(531, 816)
        self.verticalLayout = QtWidgets.QVBoxLayout(hwConfig_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(hwConfig_dialog)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.afmIpLine = QtWidgets.QLineEdit(self.groupBox)
        self.afmIpLine.setObjectName("afmIpLine")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.afmIpLine)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.afmSubPortNum = QtWidgets.QSpinBox(self.groupBox)
        self.afmSubPortNum.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.afmSubPortNum.setMaximum(100000000)
        self.afmSubPortNum.setObjectName("afmSubPortNum")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.afmSubPortNum)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.afmPubPortNum = QtWidgets.QSpinBox(self.groupBox)
        self.afmPubPortNum.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.afmPubPortNum.setMaximum(100000000)
        self.afmPubPortNum.setObjectName("afmPubPortNum")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.afmPubPortNum)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.curveNameLine = QtWidgets.QLineEdit(self.groupBox)
        self.curveNameLine.setObjectName("curveNameLine")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.curveNameLine)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.monitNameLine = QtWidgets.QLineEdit(self.groupBox)
        self.monitNameLine.setObjectName("monitNameLine")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.monitNameLine)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.xyCmdTagLine = QtWidgets.QLineEdit(self.groupBox)
        self.xyCmdTagLine.setObjectName("xyCmdTagLine")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.xyCmdTagLine)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.xyResTagLine = QtWidgets.QLineEdit(self.groupBox)
        self.xyResTagLine.setObjectName("xyResTagLine")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.xyResTagLine)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(hwConfig_dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.maxPiezoVoltNumDbl = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.maxPiezoVoltNumDbl.setMinimum(-99.0)
        self.maxPiezoVoltNumDbl.setObjectName("maxPiezoVoltNumDbl")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.maxPiezoVoltNumDbl)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.minPiezoVoltNumDbl = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.minPiezoVoltNumDbl.setMinimum(-99.0)
        self.minPiezoVoltNumDbl.setObjectName("minPiezoVoltNumDbl")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.minPiezoVoltNumDbl)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.maxPiezoExtNumDbl = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.maxPiezoExtNumDbl.setMinimum(-99.0)
        self.maxPiezoExtNumDbl.setObjectName("maxPiezoExtNumDbl")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.maxPiezoExtNumDbl)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.minPiezoExtNumDbl = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.minPiezoExtNumDbl.setMinimum(-99.0)
        self.minPiezoExtNumDbl.setObjectName("minPiezoExtNumDbl")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.minPiezoExtNumDbl)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.farNearCmbBox = QtWidgets.QComboBox(self.groupBox_2)
        self.farNearCmbBox.setObjectName("farNearCmbBox")
        self.farNearCmbBox.addItem("")
        self.farNearCmbBox.addItem("")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.farNearCmbBox)
        self.toStartSpeedNumDbl = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.toStartSpeedNumDbl.setMinimum(-99.0)
        self.toStartSpeedNumDbl.setObjectName("toStartSpeedNumDbl")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.toStartSpeedNumDbl)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_5.raise_()
        self.maxPiezoVoltNumDbl.raise_()
        self.label_6.raise_()
        self.minPiezoVoltNumDbl.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.maxPiezoExtNumDbl.raise_()
        self.minPiezoExtNumDbl.raise_()
        self.label_9.raise_()
        self.farNearCmbBox.raise_()
        self.toStartSpeedNumDbl.raise_()
        self.label_19.raise_()
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(hwConfig_dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.deflSignCmbBox = QtWidgets.QComboBox(self.groupBox_3)
        self.deflSignCmbBox.setObjectName("deflSignCmbBox")
        self.deflSignCmbBox.addItem("")
        self.deflSignCmbBox.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.deflSignCmbBox)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.sumThrNumDbl = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.sumThrNumDbl.setObjectName("sumThrNumDbl")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sumThrNumDbl)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.iGainMaxNumDbl = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.iGainMaxNumDbl.setMaximum(100000.0)
        self.iGainMaxNumDbl.setObjectName("iGainMaxNumDbl")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.iGainMaxNumDbl)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.pGainMaxNumDbl = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.pGainMaxNumDbl.setMaximum(100000.0)
        self.pGainMaxNumDbl.setObjectName("pGainMaxNumDbl")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pGainMaxNumDbl)
        self.defBaseNameLine = QtWidgets.QLineEdit(self.groupBox_3)
        self.defBaseNameLine.setObjectName("defBaseNameLine")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.defBaseNameLine)
        self.defDirLine = QtWidgets.QLineEdit(self.groupBox_3)
        self.defDirLine.setObjectName("defDirLine")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.defDirLine)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.maxDeflVoltNumDbl = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.maxDeflVoltNumDbl.setMinimum(-99.0)
        self.maxDeflVoltNumDbl.setObjectName("maxDeflVoltNumDbl")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.maxDeflVoltNumDbl)
        self.minDeflVoltNumDbl = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.minDeflVoltNumDbl.setMinimum(-99.0)
        self.minDeflVoltNumDbl.setObjectName("minDeflVoltNumDbl")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.minDeflVoltNumDbl)
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setObjectName("label_21")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.saveNcancBtnBox = QtWidgets.QDialogButtonBox(hwConfig_dialog)
        self.saveNcancBtnBox.setOrientation(QtCore.Qt.Horizontal)
        self.saveNcancBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.saveNcancBtnBox.setObjectName("saveNcancBtnBox")
        self.verticalLayout.addWidget(self.saveNcancBtnBox)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(2, 3)
        self.verticalLayout.setStretch(3, 1)

        self.retranslateUi(hwConfig_dialog)
        self.saveNcancBtnBox.accepted.connect(hwConfig_dialog.accept)
        self.saveNcancBtnBox.rejected.connect(hwConfig_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(hwConfig_dialog)

    def retranslateUi(self, hwConfig_dialog):
        _translate = QtCore.QCoreApplication.translate
        hwConfig_dialog.setWindowTitle(_translate("hwConfig_dialog", "Hardware Config"))
        self.groupBox.setTitle(_translate("hwConfig_dialog", "Connections"))
        self.label.setText(_translate("hwConfig_dialog", "AFM IP"))
        self.label_2.setText(_translate("hwConfig_dialog", "AFM Sub Port"))
        self.label_14.setText(_translate("hwConfig_dialog", "AFM Pub Port"))
        self.label_15.setText(_translate("hwConfig_dialog", "High res. device name"))
        self.label_16.setText(_translate("hwConfig_dialog", "Monitor device name"))
        self.label_3.setText(_translate("hwConfig_dialog", "XY CMD Tag"))
        self.label_4.setText(_translate("hwConfig_dialog", "XY RES Tag"))
        self.groupBox_2.setTitle(_translate("hwConfig_dialog", "Piezo settings"))
        self.label_5.setText(_translate("hwConfig_dialog", "Max Piezo voltage [V]"))
        self.label_6.setText(_translate("hwConfig_dialog", "Min Piezo voltage [V]"))
        self.label_7.setText(_translate("hwConfig_dialog", "Max Piezo ext [um]"))
        self.label_8.setText(_translate("hwConfig_dialog", "Min Piezo ext [um]"))
        self.label_9.setText(_translate("hwConfig_dialog", "Min piezo ext       ="))
        self.farNearCmbBox.setItemText(0, _translate("hwConfig_dialog", "Far"))
        self.farNearCmbBox.setItemText(1, _translate("hwConfig_dialog", "Near"))
        self.label_19.setText(_translate("hwConfig_dialog", "Start speed [nm/s]"))
        self.groupBox_3.setTitle(_translate("hwConfig_dialog", "Other"))
        self.label_10.setText(_translate("hwConfig_dialog", "Deflection sign"))
        self.deflSignCmbBox.setItemText(0, _translate("hwConfig_dialog", "Signal increase = force increase"))
        self.deflSignCmbBox.setItemText(1, _translate("hwConfig_dialog", "Signal increase = force decrease"))
        self.label_11.setText(_translate("hwConfig_dialog", "Sum Threshold [V]"))
        self.label_12.setText(_translate("hwConfig_dialog", "Integral Gain Max"))
        self.label_13.setText(_translate("hwConfig_dialog", "Proportional Gain Max"))
        self.label_17.setText(_translate("hwConfig_dialog", "Default data directory"))
        self.label_18.setText(_translate("hwConfig_dialog", "Default file base name"))
        self.label_20.setText(_translate("hwConfig_dialog", "Hi-res Defl max [V]"))
        self.label_21.setText(_translate("hwConfig_dialog", "Hi-res Defl min [V]"))

