# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ettore/GIT/CoMPlEx/GUIs/CoMPlEx_GUI.ui'
#
# Created: Mon Aug 24 17:59:51 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CoMPlEx_GUI(object):
    def setupUi(self, CoMPlEx_GUI):
        CoMPlEx_GUI.setObjectName(_fromUtf8("CoMPlEx_GUI"))
        CoMPlEx_GUI.resize(1115, 847)
        self.centralwidget = QtGui.QWidget(CoMPlEx_GUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        CoMPlEx_GUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(CoMPlEx_GUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1115, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Config = QtGui.QMenu(self.menubar)
        self.menu_Config.setObjectName(_fromUtf8("menu_Config"))
        self.menu_Config_file = QtGui.QMenu(self.menu_Config)
        self.menu_Config_file.setObjectName(_fromUtf8("menu_Config_file"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        CoMPlEx_GUI.setMenuBar(self.menubar)
        self.qpdNpiezoDock = QtGui.QDockWidget(CoMPlEx_GUI)
        self.qpdNpiezoDock.setMaximumSize(QtCore.QSize(524287, 524287))
        self.qpdNpiezoDock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.qpdNpiezoDock.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.qpdNpiezoDock.setObjectName(_fromUtf8("qpdNpiezoDock"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_2.setSizePolicy(sizePolicy)
        self.doubleSpinBox_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_2.setDecimals(3)
        self.doubleSpinBox_2.setMinimum(-10.0)
        self.doubleSpinBox_2.setMaximum(10.0)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_2, 2, 1, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        self.doubleSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox.setDecimals(3)
        self.doubleSpinBox.setMinimum(-10.0)
        self.doubleSpinBox.setMaximum(10.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout_2.addWidget(self.doubleSpinBox, 1, 1, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.dockWidgetContents)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(10)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_2.addWidget(self.progressBar, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_3.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox_3.setFont(font)
        self.doubleSpinBox_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_3.setDecimals(3)
        self.doubleSpinBox_3.setMinimum(0.0)
        self.doubleSpinBox_3.setMaximum(10.0)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_3, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.progressBar_2 = QtGui.QProgressBar(self.dockWidgetContents)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setTextVisible(False)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.gridLayout_2.addWidget(self.progressBar_2, 1, 3, 1, 1)
        self.progressBar_3 = QtGui.QProgressBar(self.dockWidgetContents)
        self.progressBar_3.setMaximum(10)
        self.progressBar_3.setProperty("value", 3)
        self.progressBar_3.setTextVisible(False)
        self.progressBar_3.setInvertedAppearance(True)
        self.progressBar_3.setObjectName(_fromUtf8("progressBar_3"))
        self.gridLayout_2.addWidget(self.progressBar_3, 2, 2, 1, 1)
        self.progressBar_4 = QtGui.QProgressBar(self.dockWidgetContents)
        self.progressBar_4.setMaximum(10)
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setTextVisible(False)
        self.progressBar_4.setObjectName(_fromUtf8("progressBar_4"))
        self.gridLayout_2.addWidget(self.progressBar_4, 2, 3, 1, 1)
        self.progressBar_5 = QtGui.QProgressBar(self.dockWidgetContents)
        self.progressBar_5.setProperty("value", 24)
        self.progressBar_5.setTextVisible(False)
        self.progressBar_5.setObjectName(_fromUtf8("progressBar_5"))
        self.gridLayout_2.addWidget(self.progressBar_5, 3, 2, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_2.setRowMinimumHeight(0, 2)
        self.gridLayout_2.setRowMinimumHeight(1, 1)
        self.gridLayout_2.setRowMinimumHeight(2, 1)
        self.gridLayout_2.setRowMinimumHeight(3, 1)
        self.gridLayout_2.setRowMinimumHeight(4, 2)
        self.gridLayout_2.setColumnStretch(0, 3)
        self.gridLayout_2.setColumnStretch(1, 3)
        self.gridLayout_2.setColumnStretch(2, 7)
        self.gridLayout_2.setColumnStretch(3, 7)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.dockWidgetContents)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.doubleSpinBox1 = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox1.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox1.setSizePolicy(sizePolicy)
        self.doubleSpinBox1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox1.setDecimals(3)
        self.doubleSpinBox1.setMaximum(10.0)
        self.doubleSpinBox1.setObjectName(_fromUtf8("doubleSpinBox1"))
        self.horizontalLayout_2.addWidget(self.doubleSpinBox1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.progressBar_6 = QtGui.QProgressBar(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_6.sizePolicy().hasHeightForWidth())
        self.progressBar_6.setSizePolicy(sizePolicy)
        self.progressBar_6.setProperty("value", 24)
        self.progressBar_6.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_6.setTextVisible(False)
        self.progressBar_6.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_6.setObjectName(_fromUtf8("progressBar_6"))
        self.horizontalLayout_3.addWidget(self.progressBar_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.graphicsView_2 = QtGui.QGraphicsView(self.dockWidgetContents)
        self.graphicsView_2.setObjectName(_fromUtf8("graphicsView_2"))
        self.horizontalLayout.addWidget(self.graphicsView_2)
        self.horizontalLayout.setStretch(0, 8)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 3)
        self.qpdNpiezoDock.setWidget(self.dockWidgetContents)
        CoMPlEx_GUI.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.qpdNpiezoDock)
        self.motorsDock = QtGui.QDockWidget(CoMPlEx_GUI)
        self.motorsDock.setMinimumSize(QtCore.QSize(330, 240))
        self.motorsDock.setMaximumSize(QtCore.QSize(330, 240))
        self.motorsDock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.motorsDock.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.motorsDock.setObjectName(_fromUtf8("motorsDock"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.motorTabs = QtGui.QTabWidget(self.dockWidgetContents_2)
        self.motorTabs.setTabPosition(QtGui.QTabWidget.South)
        self.motorTabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.motorTabs.setDocumentMode(True)
        self.motorTabs.setObjectName(_fromUtf8("motorTabs"))
        self.motCtrlTab = QtGui.QWidget()
        self.motCtrlTab.setObjectName(_fromUtf8("motCtrlTab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.motCtrlTab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_4 = QtGui.QPushButton(self.motCtrlTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_4.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_3.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.motCtrlTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_3.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_3.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.motCtrlTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_5.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_3.addWidget(self.pushButton_5, 1, 2, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.motCtrlTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_6.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_3.addWidget(self.pushButton_6, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.motCtrlTab)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 1, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_3)
        self.line = QtGui.QFrame(self.motCtrlTab)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_4.addWidget(self.line)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButton_7 = QtGui.QPushButton(self.motCtrlTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_7.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.label_6 = QtGui.QLabel(self.motCtrlTab)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.pushButton_8 = QtGui.QPushButton(self.motCtrlTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_8.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_8.setAutoDefault(False)
        self.pushButton_8.setDefault(False)
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.verticalLayout_3.addWidget(self.pushButton_8)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.line_2 = QtGui.QFrame(self.motCtrlTab)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_4.addWidget(self.line_2)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.lineEdit_2 = QtGui.QLineEdit(self.motCtrlTab)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.verticalLayout_6.addWidget(self.lineEdit_2)
        self.lineEdit_4 = QtGui.QLineEdit(self.motCtrlTab)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.verticalLayout_6.addWidget(self.lineEdit_4)
        self.pushButton = QtGui.QPushButton(self.motCtrlTab)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_6.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.motCtrlTab)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_6.addWidget(self.pushButton_2)
        self.pushButton_11 = QtGui.QPushButton(self.motCtrlTab)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.verticalLayout_6.addWidget(self.pushButton_11)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4.setStretch(0, 3)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(4, 2)
        self.motorTabs.addTab(self.motCtrlTab, _fromUtf8(""))
        self.motSetTab = QtGui.QWidget()
        self.motSetTab.setObjectName(_fromUtf8("motSetTab"))
        self.motorTabs.addTab(self.motSetTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.motorTabs)
        self.motorsDock.setWidget(self.dockWidgetContents_2)
        CoMPlEx_GUI.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.motorsDock)
        self.settingsDock = QtGui.QDockWidget(CoMPlEx_GUI)
        self.settingsDock.setMinimumSize(QtCore.QSize(361, 440))
        self.settingsDock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.settingsDock.setAllowedAreas(QtCore.Qt.RightDockWidgetArea)
        self.settingsDock.setObjectName(_fromUtf8("settingsDock"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.functionsTabs = QtGui.QTabWidget(self.dockWidgetContents_3)
        self.functionsTabs.setTabsClosable(False)
        self.functionsTabs.setObjectName(_fromUtf8("functionsTabs"))
        self.fbTab = QtGui.QWidget()
        self.fbTab.setObjectName(_fromUtf8("fbTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.fbTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pushButton_12 = QtGui.QPushButton(self.fbTab)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.gridLayout_4.addWidget(self.pushButton_12, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.fbTab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.fbTab)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_5, 1, 1, 1, 1)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.fbTab)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_4, 0, 1, 1, 1)
        self.doubleSpinBox_6 = QtGui.QDoubleSpinBox(self.fbTab)
        self.doubleSpinBox_6.setObjectName(_fromUtf8("doubleSpinBox_6"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_6, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.fbTab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.pushButton_14 = QtGui.QPushButton(self.fbTab)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.gridLayout_4.addWidget(self.pushButton_14, 2, 2, 1, 1)
        self.pushButton_13 = QtGui.QPushButton(self.fbTab)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.gridLayout_4.addWidget(self.pushButton_13, 1, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.fbTab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.fbTab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_4.addWidget(self.line_3, 3, 0, 1, 2)
        self.pushButton_15 = QtGui.QPushButton(self.fbTab)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.gridLayout_4.addWidget(self.pushButton_15, 3, 2, 1, 1)
        self.functionsTabs.addTab(self.fbTab, _fromUtf8(""))
        self.calibQpdTab = QtGui.QWidget()
        self.calibQpdTab.setObjectName(_fromUtf8("calibQpdTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.calibQpdTab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.doubleSpinBox_10 = QtGui.QDoubleSpinBox(self.calibQpdTab)
        self.doubleSpinBox_10.setObjectName(_fromUtf8("doubleSpinBox_10"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_10, 4, 1, 1, 1)
        self.doubleSpinBox_8 = QtGui.QDoubleSpinBox(self.calibQpdTab)
        self.doubleSpinBox_8.setObjectName(_fromUtf8("doubleSpinBox_8"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_8, 2, 1, 1, 1)
        self.line_4 = QtGui.QFrame(self.calibQpdTab)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_5.addWidget(self.line_4, 1, 0, 1, 3)
        self.doubleSpinBox_7 = QtGui.QDoubleSpinBox(self.calibQpdTab)
        self.doubleSpinBox_7.setObjectName(_fromUtf8("doubleSpinBox_7"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_7, 0, 1, 1, 1)
        self.pushButton_16 = QtGui.QPushButton(self.calibQpdTab)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.gridLayout_5.addWidget(self.pushButton_16, 0, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.calibQpdTab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_5.addWidget(self.label_13, 4, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.calibQpdTab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.calibQpdTab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 2, 0, 1, 1)
        self.pushButton_17 = QtGui.QPushButton(self.calibQpdTab)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.gridLayout_5.addWidget(self.pushButton_17, 2, 2, 1, 1)
        self.pushButton_18 = QtGui.QPushButton(self.calibQpdTab)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.gridLayout_5.addWidget(self.pushButton_18, 3, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.calibQpdTab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.pushButton_19 = QtGui.QPushButton(self.calibQpdTab)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.gridLayout_5.addWidget(self.pushButton_19, 4, 2, 1, 1)
        self.doubleSpinBox_9 = QtGui.QDoubleSpinBox(self.calibQpdTab)
        self.doubleSpinBox_9.setObjectName(_fromUtf8("doubleSpinBox_9"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_9, 3, 1, 1, 1)
        self.line_5 = QtGui.QFrame(self.calibQpdTab)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_5.addWidget(self.line_5, 5, 0, 1, 2)
        self.pushButton_20 = QtGui.QPushButton(self.calibQpdTab)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.gridLayout_5.addWidget(self.pushButton_20, 5, 2, 1, 1)
        self.functionsTabs.addTab(self.calibQpdTab, _fromUtf8(""))
        self.calibKTab = QtGui.QWidget()
        self.calibKTab.setObjectName(_fromUtf8("calibKTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.calibKTab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_17 = QtGui.QLabel(self.calibKTab)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_6.addWidget(self.label_17, 4, 0, 1, 1)
        self.pushButton_25 = QtGui.QPushButton(self.calibKTab)
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.gridLayout_6.addWidget(self.pushButton_25, 5, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.calibKTab)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_6.addWidget(self.label_16, 3, 0, 1, 1)
        self.pushButton_28 = QtGui.QPushButton(self.calibKTab)
        self.pushButton_28.setObjectName(_fromUtf8("pushButton_28"))
        self.gridLayout_6.addWidget(self.pushButton_28, 8, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.calibKTab)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_6.addWidget(self.label_18, 5, 0, 1, 1)
        self.pushButton_22 = QtGui.QPushButton(self.calibKTab)
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.gridLayout_6.addWidget(self.pushButton_22, 2, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.calibKTab)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_6.addWidget(self.label_20, 7, 0, 1, 1)
        self.doubleSpinBox_14 = QtGui.QDoubleSpinBox(self.calibKTab)
        self.doubleSpinBox_14.setObjectName(_fromUtf8("doubleSpinBox_14"))
        self.gridLayout_6.addWidget(self.doubleSpinBox_14, 4, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.calibKTab)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_6.addWidget(self.label_14, 0, 0, 1, 1)
        self.pushButton_24 = QtGui.QPushButton(self.calibKTab)
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.gridLayout_6.addWidget(self.pushButton_24, 4, 2, 1, 1)
        self.pushButton_21 = QtGui.QPushButton(self.calibKTab)
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.gridLayout_6.addWidget(self.pushButton_21, 0, 2, 1, 1)
        self.pushButton_26 = QtGui.QPushButton(self.calibKTab)
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.gridLayout_6.addWidget(self.pushButton_26, 6, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.calibKTab)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_6.addWidget(self.label_15, 2, 0, 1, 1)
        self.doubleSpinBox_17 = QtGui.QDoubleSpinBox(self.calibKTab)
        self.doubleSpinBox_17.setObjectName(_fromUtf8("doubleSpinBox_17"))
        self.gridLayout_6.addWidget(self.doubleSpinBox_17, 7, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.calibKTab)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_6.addWidget(self.label_21, 8, 0, 1, 1)
        self.pushButton_27 = QtGui.QPushButton(self.calibKTab)
        self.pushButton_27.setObjectName(_fromUtf8("pushButton_27"))
        self.gridLayout_6.addWidget(self.pushButton_27, 7, 2, 1, 1)
        self.line_6 = QtGui.QFrame(self.calibKTab)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_6.addWidget(self.line_6, 1, 0, 1, 3)
        self.doubleSpinBox_13 = QtGui.QDoubleSpinBox(self.calibKTab)
        self.doubleSpinBox_13.setObjectName(_fromUtf8("doubleSpinBox_13"))
        self.gridLayout_6.addWidget(self.doubleSpinBox_13, 3, 1, 1, 1)
        self.pushButton_23 = QtGui.QPushButton(self.calibKTab)
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.gridLayout_6.addWidget(self.pushButton_23, 3, 2, 1, 1)
        self.spinBox_18 = QtGui.QSpinBox(self.calibKTab)
        self.spinBox_18.setObjectName(_fromUtf8("spinBox_18"))
        self.gridLayout_6.addWidget(self.spinBox_18, 8, 1, 1, 1)
        self.doubleSpinBox_16 = QtGui.QDoubleSpinBox(self.calibKTab)
        self.doubleSpinBox_16.setObjectName(_fromUtf8("doubleSpinBox_16"))
        self.gridLayout_6.addWidget(self.doubleSpinBox_16, 6, 1, 1, 1)
        self.doubleSpinBox_12 = QtGui.QDoubleSpinBox(self.calibKTab)
        self.doubleSpinBox_12.setObjectName(_fromUtf8("doubleSpinBox_12"))
        self.gridLayout_6.addWidget(self.doubleSpinBox_12, 2, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.calibKTab)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_6.addWidget(self.label_19, 6, 0, 1, 1)
        self.doubleSpinBox_15 = QtGui.QDoubleSpinBox(self.calibKTab)
        self.doubleSpinBox_15.setObjectName(_fromUtf8("doubleSpinBox_15"))
        self.gridLayout_6.addWidget(self.doubleSpinBox_15, 5, 1, 1, 1)
        self.doubleSpinBox_11 = QtGui.QDoubleSpinBox(self.calibKTab)
        self.doubleSpinBox_11.setObjectName(_fromUtf8("doubleSpinBox_11"))
        self.gridLayout_6.addWidget(self.doubleSpinBox_11, 0, 1, 1, 1)
        self.line_7 = QtGui.QFrame(self.calibKTab)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_6.addWidget(self.line_7, 9, 0, 1, 2)
        self.pushButton_29 = QtGui.QPushButton(self.calibKTab)
        self.pushButton_29.setObjectName(_fromUtf8("pushButton_29"))
        self.gridLayout_6.addWidget(self.pushButton_29, 9, 2, 1, 1)
        self.functionsTabs.addTab(self.calibKTab, _fromUtf8(""))
        self.fvsdTab = QtGui.QWidget()
        self.fvsdTab.setObjectName(_fromUtf8("fvsdTab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.fvsdTab)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.doubleSpinBox_23 = QtGui.QDoubleSpinBox(self.fvsdTab)
        self.doubleSpinBox_23.setObjectName(_fromUtf8("doubleSpinBox_23"))
        self.gridLayout_7.addWidget(self.doubleSpinBox_23, 5, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.fvsdTab)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_7.addWidget(self.label_26, 4, 0, 1, 1)
        self.pushButton_36 = QtGui.QPushButton(self.fvsdTab)
        self.pushButton_36.setObjectName(_fromUtf8("pushButton_36"))
        self.gridLayout_7.addWidget(self.pushButton_36, 7, 2, 1, 1)
        self.doubleSpinBox_20 = QtGui.QDoubleSpinBox(self.fvsdTab)
        self.doubleSpinBox_20.setObjectName(_fromUtf8("doubleSpinBox_20"))
        self.gridLayout_7.addWidget(self.doubleSpinBox_20, 2, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.fvsdTab)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_7.addWidget(self.label_23, 1, 0, 1, 1)
        self.pushButton_31 = QtGui.QPushButton(self.fvsdTab)
        self.pushButton_31.setObjectName(_fromUtf8("pushButton_31"))
        self.gridLayout_7.addWidget(self.pushButton_31, 1, 2, 1, 1)
        self.pushButton_34 = QtGui.QPushButton(self.fvsdTab)
        self.pushButton_34.setObjectName(_fromUtf8("pushButton_34"))
        self.gridLayout_7.addWidget(self.pushButton_34, 4, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.fvsdTab)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_7.addWidget(self.label_24, 2, 0, 1, 1)
        self.doubleSpinBox_18 = QtGui.QDoubleSpinBox(self.fvsdTab)
        self.doubleSpinBox_18.setObjectName(_fromUtf8("doubleSpinBox_18"))
        self.gridLayout_7.addWidget(self.doubleSpinBox_18, 0, 1, 1, 1)
        self.pushButton_35 = QtGui.QPushButton(self.fvsdTab)
        self.pushButton_35.setObjectName(_fromUtf8("pushButton_35"))
        self.gridLayout_7.addWidget(self.pushButton_35, 5, 2, 1, 1)
        self.label_22 = QtGui.QLabel(self.fvsdTab)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_7.addWidget(self.label_22, 0, 0, 1, 1)
        self.line_8 = QtGui.QFrame(self.fvsdTab)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_7.addWidget(self.line_8, 7, 0, 1, 2)
        self.pushButton_33 = QtGui.QPushButton(self.fvsdTab)
        self.pushButton_33.setObjectName(_fromUtf8("pushButton_33"))
        self.gridLayout_7.addWidget(self.pushButton_33, 3, 2, 1, 1)
        self.label_27 = QtGui.QLabel(self.fvsdTab)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_7.addWidget(self.label_27, 5, 0, 1, 1)
        self.doubleSpinBox_24 = QtGui.QDoubleSpinBox(self.fvsdTab)
        self.doubleSpinBox_24.setObjectName(_fromUtf8("doubleSpinBox_24"))
        self.gridLayout_7.addWidget(self.doubleSpinBox_24, 9, 1, 1, 1)
        self.doubleSpinBox_19 = QtGui.QDoubleSpinBox(self.fvsdTab)
        self.doubleSpinBox_19.setObjectName(_fromUtf8("doubleSpinBox_19"))
        self.gridLayout_7.addWidget(self.doubleSpinBox_19, 1, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.fvsdTab)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_7.addWidget(self.checkBox, 8, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.fvsdTab)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_7.addWidget(self.label_25, 3, 0, 1, 1)
        self.pushButton_30 = QtGui.QPushButton(self.fvsdTab)
        self.pushButton_30.setObjectName(_fromUtf8("pushButton_30"))
        self.gridLayout_7.addWidget(self.pushButton_30, 0, 2, 1, 1)
        self.doubleSpinBox_22 = QtGui.QDoubleSpinBox(self.fvsdTab)
        self.doubleSpinBox_22.setObjectName(_fromUtf8("doubleSpinBox_22"))
        self.gridLayout_7.addWidget(self.doubleSpinBox_22, 4, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.fvsdTab)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_7.addWidget(self.label_28, 9, 0, 1, 1)
        self.pushButton_32 = QtGui.QPushButton(self.fvsdTab)
        self.pushButton_32.setObjectName(_fromUtf8("pushButton_32"))
        self.gridLayout_7.addWidget(self.pushButton_32, 2, 2, 1, 1)
        self.doubleSpinBox_21 = QtGui.QDoubleSpinBox(self.fvsdTab)
        self.doubleSpinBox_21.setObjectName(_fromUtf8("doubleSpinBox_21"))
        self.gridLayout_7.addWidget(self.doubleSpinBox_21, 3, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.fvsdTab)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_7.addWidget(self.label_32, 6, 0, 1, 1)
        self.pushButton_39 = QtGui.QPushButton(self.fvsdTab)
        self.pushButton_39.setObjectName(_fromUtf8("pushButton_39"))
        self.gridLayout_7.addWidget(self.pushButton_39, 6, 2, 1, 1)
        self.spinBox_28 = QtGui.QSpinBox(self.fvsdTab)
        self.spinBox_28.setObjectName(_fromUtf8("spinBox_28"))
        self.gridLayout_7.addWidget(self.spinBox_28, 6, 1, 1, 1)
        self.functionsTabs.addTab(self.fvsdTab, _fromUtf8(""))
        self.custFvsdTab = QtGui.QWidget()
        self.custFvsdTab.setObjectName(_fromUtf8("custFvsdTab"))
        self.gridLayout_8 = QtGui.QGridLayout(self.custFvsdTab)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.line_9 = QtGui.QFrame(self.custFvsdTab)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout_8.addWidget(self.line_9, 1, 0, 1, 3)
        self.doubleSpinBox_25 = QtGui.QDoubleSpinBox(self.custFvsdTab)
        self.doubleSpinBox_25.setObjectName(_fromUtf8("doubleSpinBox_25"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_25, 0, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.custFvsdTab)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_8.addWidget(self.label_34, 5, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.custFvsdTab)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_8.addWidget(self.label_30, 2, 0, 1, 1)
        self.doubleSpinBox_26 = QtGui.QDoubleSpinBox(self.custFvsdTab)
        self.doubleSpinBox_26.setObjectName(_fromUtf8("doubleSpinBox_26"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_26, 2, 1, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.custFvsdTab)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.comboBox_3, 5, 1, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.custFvsdTab)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.gridLayout_8.addWidget(self.comboBox_2, 9, 0, 1, 2)
        self.label_33 = QtGui.QLabel(self.custFvsdTab)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_8.addWidget(self.label_33, 4, 0, 1, 1)
        self.pushButton_38 = QtGui.QPushButton(self.custFvsdTab)
        self.pushButton_38.setObjectName(_fromUtf8("pushButton_38"))
        self.gridLayout_8.addWidget(self.pushButton_38, 9, 2, 1, 1)
        self.label_29 = QtGui.QLabel(self.custFvsdTab)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_8.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.custFvsdTab)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_8.addWidget(self.label_31, 3, 0, 1, 1)
        self.doubleSpinBox_27 = QtGui.QDoubleSpinBox(self.custFvsdTab)
        self.doubleSpinBox_27.setObjectName(_fromUtf8("doubleSpinBox_27"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_27, 3, 1, 1, 1)
        self.pushButton_37 = QtGui.QPushButton(self.custFvsdTab)
        self.pushButton_37.setObjectName(_fromUtf8("pushButton_37"))
        self.gridLayout_8.addWidget(self.pushButton_37, 0, 2, 1, 1)
        self.label_35 = QtGui.QLabel(self.custFvsdTab)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_8.addWidget(self.label_35, 6, 0, 1, 1)
        self.pushButton_40 = QtGui.QPushButton(self.custFvsdTab)
        self.pushButton_40.setObjectName(_fromUtf8("pushButton_40"))
        self.gridLayout_8.addWidget(self.pushButton_40, 8, 0, 1, 2)
        self.doubleSpinBox_29 = QtGui.QDoubleSpinBox(self.custFvsdTab)
        self.doubleSpinBox_29.setEnabled(False)
        self.doubleSpinBox_29.setObjectName(_fromUtf8("doubleSpinBox_29"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_29, 6, 1, 1, 1)
        self.spinBox_281 = QtGui.QSpinBox(self.custFvsdTab)
        self.spinBox_281.setObjectName(_fromUtf8("spinBox_281"))
        self.gridLayout_8.addWidget(self.spinBox_281, 4, 1, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.custFvsdTab)
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_8.addWidget(self.checkBox_2, 7, 0, 1, 1)
        self.pushButton_41 = QtGui.QPushButton(self.custFvsdTab)
        self.pushButton_41.setObjectName(_fromUtf8("pushButton_41"))
        self.gridLayout_8.addWidget(self.pushButton_41, 10, 0, 1, 3)
        self.functionsTabs.addTab(self.custFvsdTab, _fromUtf8(""))
        self.mapTab = QtGui.QWidget()
        self.mapTab.setObjectName(_fromUtf8("mapTab"))
        self.gridLayout_9 = QtGui.QGridLayout(self.mapTab)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem2, 3, 1, 1, 1)
        self.spinBox_29 = QtGui.QSpinBox(self.mapTab)
        self.spinBox_29.setObjectName(_fromUtf8("spinBox_29"))
        self.gridLayout_9.addWidget(self.spinBox_29, 0, 1, 1, 1)
        self.label_36 = QtGui.QLabel(self.mapTab)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_9.addWidget(self.label_36, 0, 0, 1, 1)
        self.spinBox_31 = QtGui.QSpinBox(self.mapTab)
        self.spinBox_31.setObjectName(_fromUtf8("spinBox_31"))
        self.gridLayout_9.addWidget(self.spinBox_31, 2, 1, 1, 1)
        self.spinBox_30 = QtGui.QSpinBox(self.mapTab)
        self.spinBox_30.setObjectName(_fromUtf8("spinBox_30"))
        self.gridLayout_9.addWidget(self.spinBox_30, 1, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.mapTab)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_9.addWidget(self.label_37, 1, 0, 1, 1)
        self.label_38 = QtGui.QLabel(self.mapTab)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_9.addWidget(self.label_38, 2, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem3, 1, 2, 1, 1)
        self.functionsTabs.addTab(self.mapTab, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.functionsTabs)
        self.settingsDock.setWidget(self.dockWidgetContents_3)
        CoMPlEx_GUI.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.settingsDock)
        self.remoteDock = QtGui.QDockWidget(CoMPlEx_GUI)
        self.remoteDock.setMinimumSize(QtCore.QSize(251, 130))
        self.remoteDock.setMaximumSize(QtCore.QSize(524287, 130))
        self.remoteDock.setObjectName(_fromUtf8("remoteDock"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.comboBox = QtGui.QComboBox(self.dockWidgetContents_4)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.comboBox)
        self.lineEdit = QtGui.QLineEdit(self.dockWidgetContents_4)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton_9 = QtGui.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_9.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_5.addWidget(self.pushButton_9)
        self.pushButton_10 = QtGui.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_10.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout_5.addWidget(self.pushButton_10)
        self.progressBar_7 = QtGui.QProgressBar(self.dockWidgetContents_4)
        self.progressBar_7.setProperty("value", 24)
        self.progressBar_7.setObjectName(_fromUtf8("progressBar_7"))
        self.horizontalLayout_5.addWidget(self.progressBar_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.remoteDock.setWidget(self.dockWidgetContents_4)
        CoMPlEx_GUI.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.remoteDock)
        self.action_Set_save_paths = QtGui.QAction(CoMPlEx_GUI)
        self.action_Set_save_paths.setObjectName(_fromUtf8("action_Set_save_paths"))
        self.action_QPD_and_piezo = QtGui.QAction(CoMPlEx_GUI)
        self.action_QPD_and_piezo.setCheckable(True)
        self.action_QPD_and_piezo.setChecked(True)
        self.action_QPD_and_piezo.setObjectName(_fromUtf8("action_QPD_and_piezo"))
        self.action_Motors = QtGui.QAction(CoMPlEx_GUI)
        self.action_Motors.setCheckable(True)
        self.action_Motors.setChecked(True)
        self.action_Motors.setObjectName(_fromUtf8("action_Motors"))
        self.action_General_config = QtGui.QAction(CoMPlEx_GUI)
        self.action_General_config.setObjectName(_fromUtf8("action_General_config"))
        self.action_Controls_config = QtGui.QAction(CoMPlEx_GUI)
        self.action_Controls_config.setObjectName(_fromUtf8("action_Controls_config"))
        self.action_Settings = QtGui.QAction(CoMPlEx_GUI)
        self.action_Settings.setCheckable(True)
        self.action_Settings.setChecked(True)
        self.action_Settings.setObjectName(_fromUtf8("action_Settings"))
        self.action_Remote = QtGui.QAction(CoMPlEx_GUI)
        self.action_Remote.setCheckable(True)
        self.action_Remote.setChecked(True)
        self.action_Remote.setObjectName(_fromUtf8("action_Remote"))
        self.menu_Config_file.addAction(self.action_General_config)
        self.menu_Config_file.addAction(self.action_Controls_config)
        self.menu_Config.addAction(self.menu_Config_file.menuAction())
        self.menu_Config.addAction(self.action_Set_save_paths)
        self.menu_View.addAction(self.action_QPD_and_piezo)
        self.menu_View.addAction(self.action_Motors)
        self.menu_View.addAction(self.action_Settings)
        self.menu_View.addAction(self.action_Remote)
        self.menubar.addAction(self.menu_Config.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())

        self.retranslateUi(CoMPlEx_GUI)
        self.motorTabs.setCurrentIndex(0)
        self.functionsTabs.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(CoMPlEx_GUI)

    def retranslateUi(self, CoMPlEx_GUI):
        CoMPlEx_GUI.setWindowTitle(_translate("CoMPlEx_GUI", "MainWindow", None))
        self.menu_Config.setTitle(_translate("CoMPlEx_GUI", "&File", None))
        self.menu_Config_file.setTitle(_translate("CoMPlEx_GUI", "&Config file", None))
        self.menu_View.setTitle(_translate("CoMPlEx_GUI", "&View", None))
        self.qpdNpiezoDock.setWindowTitle(_translate("CoMPlEx_GUI", "QPD and piezo monitor", None))
        self.label_3.setText(_translate("CoMPlEx_GUI", "Sum [V]", None))
        self.label.setText(_translate("CoMPlEx_GUI", "Deflection [V]", None))
        self.label_2.setText(_translate("CoMPlEx_GUI", "Torsion [V]", None))
        self.label_4.setText(_translate("CoMPlEx_GUI", "Z [um]", None))
        self.motorsDock.setWindowTitle(_translate("CoMPlEx_GUI", "Motors", None))
        self.pushButton_4.setText(_translate("CoMPlEx_GUI", "ᐃ", None))
        self.pushButton_3.setText(_translate("CoMPlEx_GUI", "ᐊ", None))
        self.pushButton_5.setText(_translate("CoMPlEx_GUI", "ᐅ", None))
        self.pushButton_6.setText(_translate("CoMPlEx_GUI", "ᐁ", None))
        self.label_5.setText(_translate("CoMPlEx_GUI", "XY", None))
        self.pushButton_7.setText(_translate("CoMPlEx_GUI", "ᐃ", None))
        self.label_6.setText(_translate("CoMPlEx_GUI", "z", None))
        self.pushButton_8.setText(_translate("CoMPlEx_GUI", "ᐁ", None))
        self.pushButton.setText(_translate("CoMPlEx_GUI", "Reset X", None))
        self.pushButton_2.setText(_translate("CoMPlEx_GUI", "Reset Y", None))
        self.pushButton_11.setText(_translate("CoMPlEx_GUI", "Reset Z", None))
        self.motorTabs.setTabText(self.motorTabs.indexOf(self.motCtrlTab), _translate("CoMPlEx_GUI", "Controls", None))
        self.motorTabs.setTabText(self.motorTabs.indexOf(self.motSetTab), _translate("CoMPlEx_GUI", "Settings", None))
        self.settingsDock.setWindowTitle(_translate("CoMPlEx_GUI", "Settings", None))
        self.pushButton_12.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_7.setText(_translate("CoMPlEx_GUI", "Set Point [V]", None))
        self.label_8.setText(_translate("CoMPlEx_GUI", "P Gain", None))
        self.pushButton_14.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.pushButton_13.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_9.setText(_translate("CoMPlEx_GUI", "I Gain", None))
        self.pushButton_15.setText(_translate("CoMPlEx_GUI", "Upload All", None))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.fbTab), _translate("CoMPlEx_GUI", "Feedback", None))
        self.pushButton_16.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_13.setText(_translate("CoMPlEx_GUI", "Frequency [Hz]", None))
        self.label_12.setText(_translate("CoMPlEx_GUI", "Amplitude [nm]", None))
        self.label_11.setText(_translate("CoMPlEx_GUI", "Z offset [nm]", None))
        self.pushButton_17.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.pushButton_18.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_10.setText(_translate("CoMPlEx_GUI", "Kd [nm/V]", None))
        self.pushButton_19.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.pushButton_20.setText(_translate("CoMPlEx_GUI", "Upload All", None))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.calibQpdTab), _translate("CoMPlEx_GUI", "QPD Calibration", None))
        self.label_17.setText(_translate("CoMPlEx_GUI", "Cant. Length [nm]", None))
        self.pushButton_25.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_16.setText(_translate("CoMPlEx_GUI", "Peak end freq[Hz]", None))
        self.pushButton_28.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_18.setText(_translate("CoMPlEx_GUI", "Cant. Width [nm]", None))
        self.pushButton_22.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_20.setText(_translate("CoMPlEx_GUI", "Medium visc. [nm]", None))
        self.label_14.setText(_translate("CoMPlEx_GUI", "K [pN/nm]", None))
        self.pushButton_24.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.pushButton_21.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.pushButton_26.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_15.setText(_translate("CoMPlEx_GUI", "Peak start freq[Hz]", None))
        self.label_21.setText(_translate("CoMPlEx_GUI", "Average Num", None))
        self.pushButton_27.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.pushButton_23.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_19.setText(_translate("CoMPlEx_GUI", "Medium dens. [nm]", None))
        self.pushButton_29.setText(_translate("CoMPlEx_GUI", "Upload All", None))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.calibKTab), _translate("CoMPlEx_GUI", "K Calibration", None))
        self.label_26.setText(_translate("CoMPlEx_GUI", "Retr. speed [nm/s]", None))
        self.pushButton_36.setText(_translate("CoMPlEx_GUI", "Upload All", None))
        self.label_23.setText(_translate("CoMPlEx_GUI", "Start Z [nm]", None))
        self.pushButton_31.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.pushButton_34.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_24.setText(_translate("CoMPlEx_GUI", "End Z [nm]", None))
        self.pushButton_35.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_22.setText(_translate("CoMPlEx_GUI", "Max Force [pN]", None))
        self.pushButton_33.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_27.setText(_translate("CoMPlEx_GUI", "Hold time [s]", None))
        self.checkBox.setText(_translate("CoMPlEx_GUI", "Constant Force", None))
        self.label_25.setText(_translate("CoMPlEx_GUI", "App. speed [nm/s]", None))
        self.pushButton_30.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_28.setText(_translate("CoMPlEx_GUI", "Curves number", None))
        self.pushButton_32.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_32.setText(_translate("CoMPlEx_GUI", "Points number", None))
        self.pushButton_39.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.fvsdTab), _translate("CoMPlEx_GUI", "FvsD", None))
        self.label_34.setText(_translate("CoMPlEx_GUI", "Direction", None))
        self.label_30.setText(_translate("CoMPlEx_GUI", "End Z [nm]", None))
        self.comboBox_3.setItemText(0, _translate("CoMPlEx_GUI", "Far", None))
        self.comboBox_3.setItemText(1, _translate("CoMPlEx_GUI", "Near", None))
        self.comboBox_3.setItemText(2, _translate("CoMPlEx_GUI", "Hold", None))
        self.label_33.setText(_translate("CoMPlEx_GUI", "Points number", None))
        self.pushButton_38.setText(_translate("CoMPlEx_GUI", "Remove", None))
        self.label_29.setText(_translate("CoMPlEx_GUI", "Start Z [nm]", None))
        self.label_31.setText(_translate("CoMPlEx_GUI", "End Force [pN]", None))
        self.pushButton_37.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_35.setText(_translate("CoMPlEx_GUI", "Hold Time [s]", None))
        self.pushButton_40.setText(_translate("CoMPlEx_GUI", "ADD", None))
        self.checkBox_2.setText(_translate("CoMPlEx_GUI", "Constant Force", None))
        self.pushButton_41.setText(_translate("CoMPlEx_GUI", "Show Z travel preview", None))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.custFvsdTab), _translate("CoMPlEx_GUI", "Custom FvsD", None))
        self.label_36.setText(_translate("CoMPlEx_GUI", "X steps number", None))
        self.label_37.setText(_translate("CoMPlEx_GUI", "Y steps number", None))
        self.label_38.setText(_translate("CoMPlEx_GUI", "Points number", None))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.mapTab), _translate("CoMPlEx_GUI", "Map", None))
        self.remoteDock.setWindowTitle(_translate("CoMPlEx_GUI", "Remote", None))
        self.comboBox.setItemText(0, _translate("CoMPlEx_GUI", "Engage", None))
        self.comboBox.setItemText(1, _translate("CoMPlEx_GUI", "Calibrate QPD", None))
        self.comboBox.setItemText(2, _translate("CoMPlEx_GUI", "Calibrate K", None))
        self.comboBox.setItemText(3, _translate("CoMPlEx_GUI", "Single Curve", None))
        self.comboBox.setItemText(4, _translate("CoMPlEx_GUI", "Single Custom Curve", None))
        self.comboBox.setItemText(5, _translate("CoMPlEx_GUI", "Curve Map", None))
        self.comboBox.setItemText(6, _translate("CoMPlEx_GUI", "Custom Curve Map", None))
        self.pushButton_9.setText(_translate("CoMPlEx_GUI", "     ▶", None))
        self.pushButton_10.setText(_translate("CoMPlEx_GUI", "■ ", None))
        self.action_Set_save_paths.setText(_translate("CoMPlEx_GUI", "&Set save paths", None))
        self.action_QPD_and_piezo.setText(_translate("CoMPlEx_GUI", "&QPD and piezo", None))
        self.action_Motors.setText(_translate("CoMPlEx_GUI", "&Motors", None))
        self.action_General_config.setText(_translate("CoMPlEx_GUI", "&General config", None))
        self.action_Controls_config.setText(_translate("CoMPlEx_GUI", "&Controls config", None))
        self.action_Settings.setText(_translate("CoMPlEx_GUI", "&Settings", None))
        self.action_Remote.setText(_translate("CoMPlEx_GUI", "&Remote", None))

