# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIs\CoMPlEx_MainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CoMPlEx_GUI(object):
    def setupUi(self, CoMPlEx_GUI):
        CoMPlEx_GUI.setObjectName("CoMPlEx_GUI")
        CoMPlEx_GUI.resize(1115, 896)
        self.centralwidget = QtWidgets.QWidget(CoMPlEx_GUI)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.centralPlot = PlotWidget(self.centralwidget)
        self.centralPlot.setObjectName("centralPlot")
        self.gridLayout.addWidget(self.centralPlot, 0, 0, 1, 1)
        CoMPlEx_GUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CoMPlEx_GUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1115, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Config = QtWidgets.QMenu(self.menubar)
        self.menu_Config.setObjectName("menu_Config")
        self.menu_View = QtWidgets.QMenu(self.menubar)
        self.menu_View.setObjectName("menu_View")
        self.menu_Analysis = QtWidgets.QMenu(self.menubar)
        self.menu_Analysis.setObjectName("menu_Analysis")
        CoMPlEx_GUI.setMenuBar(self.menubar)
        self.qpdNpiezoDock = QtWidgets.QDockWidget(CoMPlEx_GUI)
        self.qpdNpiezoDock.setMaximumSize(QtCore.QSize(524287, 524287))
        self.qpdNpiezoDock.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.qpdNpiezoDock.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.qpdNpiezoDock.setObjectName("qpdNpiezoDock")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.torsNumDbl = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.torsNumDbl.sizePolicy().hasHeightForWidth())
        self.torsNumDbl.setSizePolicy(sizePolicy)
        self.torsNumDbl.setReadOnly(True)
        self.torsNumDbl.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.torsNumDbl.setDecimals(3)
        self.torsNumDbl.setMinimum(-10.0)
        self.torsNumDbl.setMaximum(10.0)
        self.torsNumDbl.setObjectName("torsNumDbl")
        self.gridLayout_2.addWidget(self.torsNumDbl, 2, 1, 1, 1)
        self.deflNumDbl = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deflNumDbl.sizePolicy().hasHeightForWidth())
        self.deflNumDbl.setSizePolicy(sizePolicy)
        self.deflNumDbl.setReadOnly(True)
        self.deflNumDbl.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.deflNumDbl.setDecimals(3)
        self.deflNumDbl.setMinimum(-10.0)
        self.deflNumDbl.setMaximum(10.0)
        self.deflNumDbl.setObjectName("deflNumDbl")
        self.gridLayout_2.addWidget(self.deflNumDbl, 1, 1, 1, 1)
        self.deflNegProg = QtWidgets.QProgressBar(self.dockWidgetContents)
        self.deflNegProg.setAutoFillBackground(False)
        self.deflNegProg.setMinimum(0)
        self.deflNegProg.setMaximum(10)
        self.deflNegProg.setProperty("value", 0)
        self.deflNegProg.setTextVisible(False)
        self.deflNegProg.setInvertedAppearance(True)
        self.deflNegProg.setObjectName("deflNegProg")
        self.gridLayout_2.addWidget(self.deflNegProg, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.sumNumDbl = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sumNumDbl.sizePolicy().hasHeightForWidth())
        self.sumNumDbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sumNumDbl.setFont(font)
        self.sumNumDbl.setReadOnly(True)
        self.sumNumDbl.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sumNumDbl.setDecimals(3)
        self.sumNumDbl.setMinimum(0.0)
        self.sumNumDbl.setMaximum(10.0)
        self.sumNumDbl.setObjectName("sumNumDbl")
        self.gridLayout_2.addWidget(self.sumNumDbl, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.deflPosProg = QtWidgets.QProgressBar(self.dockWidgetContents)
        self.deflPosProg.setMaximum(10)
        self.deflPosProg.setProperty("value", 0)
        self.deflPosProg.setTextVisible(False)
        self.deflPosProg.setObjectName("deflPosProg")
        self.gridLayout_2.addWidget(self.deflPosProg, 1, 3, 1, 1)
        self.torsNegProg = QtWidgets.QProgressBar(self.dockWidgetContents)
        self.torsNegProg.setMaximum(10)
        self.torsNegProg.setProperty("value", 0)
        self.torsNegProg.setTextVisible(False)
        self.torsNegProg.setInvertedAppearance(True)
        self.torsNegProg.setObjectName("torsNegProg")
        self.gridLayout_2.addWidget(self.torsNegProg, 2, 2, 1, 1)
        self.torsPosProg = QtWidgets.QProgressBar(self.dockWidgetContents)
        self.torsPosProg.setMaximum(10)
        self.torsPosProg.setProperty("value", 0)
        self.torsPosProg.setTextVisible(False)
        self.torsPosProg.setObjectName("torsPosProg")
        self.gridLayout_2.addWidget(self.torsPosProg, 2, 3, 1, 1)
        self.sumProg = QtWidgets.QProgressBar(self.dockWidgetContents)
        self.sumProg.setMaximum(10)
        self.sumProg.setProperty("value", 0)
        self.sumProg.setTextVisible(False)
        self.sumProg.setObjectName("sumProg")
        self.gridLayout_2.addWidget(self.sumProg, 3, 2, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_2.setRowMinimumHeight(0, 2)
        self.gridLayout_2.setRowMinimumHeight(1, 1)
        self.gridLayout_2.setRowMinimumHeight(2, 1)
        self.gridLayout_2.setRowMinimumHeight(3, 1)
        self.gridLayout_2.setRowMinimumHeight(4, 2)
        self.gridLayout_2.setColumnStretch(0, 3)
        self.gridLayout_2.setColumnStretch(1, 3)
        self.gridLayout_2.setColumnStretch(2, 7)
        self.gridLayout_2.setColumnStretch(3, 7)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.zPiezoNumDbl = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zPiezoNumDbl.sizePolicy().hasHeightForWidth())
        self.zPiezoNumDbl.setSizePolicy(sizePolicy)
        self.zPiezoNumDbl.setReadOnly(True)
        self.zPiezoNumDbl.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.zPiezoNumDbl.setDecimals(3)
        self.zPiezoNumDbl.setMaximum(10.0)
        self.zPiezoNumDbl.setObjectName("zPiezoNumDbl")
        self.horizontalLayout_2.addWidget(self.zPiezoNumDbl)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.zPiezoProg = QtWidgets.QProgressBar(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zPiezoProg.sizePolicy().hasHeightForWidth())
        self.zPiezoProg.setSizePolicy(sizePolicy)
        self.zPiezoProg.setMaximum(10)
        self.zPiezoProg.setProperty("value", 0)
        self.zPiezoProg.setAlignment(QtCore.Qt.AlignCenter)
        self.zPiezoProg.setTextVisible(False)
        self.zPiezoProg.setOrientation(QtCore.Qt.Vertical)
        self.zPiezoProg.setObjectName("zPiezoProg")
        self.horizontalLayout_3.addWidget(self.zPiezoProg)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.alignPlot = PlotWidget(self.dockWidgetContents)
        self.alignPlot.setObjectName("alignPlot")
        self.horizontalLayout.addWidget(self.alignPlot)
        self.horizontalLayout.setStretch(0, 8)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 3)
        self.qpdNpiezoDock.setWidget(self.dockWidgetContents)
        CoMPlEx_GUI.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.qpdNpiezoDock)
        self.motorsDock = QtWidgets.QDockWidget(CoMPlEx_GUI)
        self.motorsDock.setMinimumSize(QtCore.QSize(330, 240))
        self.motorsDock.setMaximumSize(QtCore.QSize(330, 240))
        self.motorsDock.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.motorsDock.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.motorsDock.setObjectName("motorsDock")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.motorTabs = QtWidgets.QTabWidget(self.dockWidgetContents_2)
        self.motorTabs.setTabPosition(QtWidgets.QTabWidget.South)
        self.motorTabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.motorTabs.setDocumentMode(True)
        self.motorTabs.setObjectName("motorTabs")
        self.motManTab = QtWidgets.QWidget()
        self.motManTab.setObjectName("motManTab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.motManTab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.yPlusBtn = QtWidgets.QPushButton(self.motManTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yPlusBtn.sizePolicy().hasHeightForWidth())
        self.yPlusBtn.setSizePolicy(sizePolicy)
        self.yPlusBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.yPlusBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.yPlusBtn.setObjectName("yPlusBtn")
        self.gridLayout_3.addWidget(self.yPlusBtn, 0, 1, 1, 1)
        self.xMinusBtn = QtWidgets.QPushButton(self.motManTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xMinusBtn.sizePolicy().hasHeightForWidth())
        self.xMinusBtn.setSizePolicy(sizePolicy)
        self.xMinusBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.xMinusBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.xMinusBtn.setObjectName("xMinusBtn")
        self.gridLayout_3.addWidget(self.xMinusBtn, 1, 0, 1, 1)
        self.xPlusBtn = QtWidgets.QPushButton(self.motManTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xPlusBtn.sizePolicy().hasHeightForWidth())
        self.xPlusBtn.setSizePolicy(sizePolicy)
        self.xPlusBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.xPlusBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.xPlusBtn.setObjectName("xPlusBtn")
        self.gridLayout_3.addWidget(self.xPlusBtn, 1, 2, 1, 1)
        self.yMinusBtn = QtWidgets.QPushButton(self.motManTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yMinusBtn.sizePolicy().hasHeightForWidth())
        self.yMinusBtn.setSizePolicy(sizePolicy)
        self.yMinusBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.yMinusBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.yMinusBtn.setObjectName("yMinusBtn")
        self.gridLayout_3.addWidget(self.yMinusBtn, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.motManTab)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.goCenterBtn = QtWidgets.QPushButton(self.motManTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goCenterBtn.sizePolicy().hasHeightForWidth())
        self.goCenterBtn.setSizePolicy(sizePolicy)
        self.goCenterBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.goCenterBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.goCenterBtn.setObjectName("goCenterBtn")
        self.gridLayout_3.addWidget(self.goCenterBtn, 1, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_3)
        self.line = QtWidgets.QFrame(self.motManTab)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.zPlusBtn = QtWidgets.QPushButton(self.motManTab)
        self.zPlusBtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zPlusBtn.sizePolicy().hasHeightForWidth())
        self.zPlusBtn.setSizePolicy(sizePolicy)
        self.zPlusBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.zPlusBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.zPlusBtn.setObjectName("zPlusBtn")
        self.verticalLayout_3.addWidget(self.zPlusBtn)
        self.label_6 = QtWidgets.QLabel(self.motManTab)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.zMinusBtn = QtWidgets.QPushButton(self.motManTab)
        self.zMinusBtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zMinusBtn.sizePolicy().hasHeightForWidth())
        self.zMinusBtn.setSizePolicy(sizePolicy)
        self.zMinusBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.zMinusBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.zMinusBtn.setAutoDefault(False)
        self.zMinusBtn.setDefault(False)
        self.zMinusBtn.setFlat(False)
        self.zMinusBtn.setObjectName("zMinusBtn")
        self.verticalLayout_3.addWidget(self.zMinusBtn)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.line_2 = QtWidgets.QFrame(self.motManTab)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_4.addWidget(self.line_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.xStepsLine = QtWidgets.QLineEdit(self.motManTab)
        self.xStepsLine.setEnabled(False)
        self.xStepsLine.setReadOnly(True)
        self.xStepsLine.setObjectName("xStepsLine")
        self.verticalLayout_6.addWidget(self.xStepsLine)
        self.yStepsLine = QtWidgets.QLineEdit(self.motManTab)
        self.yStepsLine.setEnabled(False)
        self.yStepsLine.setReadOnly(True)
        self.yStepsLine.setObjectName("yStepsLine")
        self.verticalLayout_6.addWidget(self.yStepsLine)
        self.zStepsLine = QtWidgets.QLineEdit(self.motManTab)
        self.zStepsLine.setEnabled(False)
        self.zStepsLine.setAlignment(QtCore.Qt.AlignCenter)
        self.zStepsLine.setReadOnly(True)
        self.zStepsLine.setObjectName("zStepsLine")
        self.verticalLayout_6.addWidget(self.zStepsLine)
        self.resetXYBtn = QtWidgets.QPushButton(self.motManTab)
        self.resetXYBtn.setObjectName("resetXYBtn")
        self.verticalLayout_6.addWidget(self.resetXYBtn)
        self.resetZBtn = QtWidgets.QPushButton(self.motManTab)
        self.resetZBtn.setEnabled(False)
        self.resetZBtn.setObjectName("resetZBtn")
        self.verticalLayout_6.addWidget(self.resetZBtn)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4.setStretch(0, 3)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(4, 2)
        self.motorTabs.addTab(self.motManTab, "")
        self.motAutoTab = QtWidgets.QWidget()
        self.motAutoTab.setEnabled(False)
        self.motAutoTab.setObjectName("motAutoTab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.motAutoTab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.downRightBtn = QtWidgets.QPushButton(self.motAutoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downRightBtn.sizePolicy().hasHeightForWidth())
        self.downRightBtn.setSizePolicy(sizePolicy)
        self.downRightBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.downRightBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.downRightBtn.setObjectName("downRightBtn")
        self.gridLayout_9.addWidget(self.downRightBtn, 2, 2, 1, 1)
        self.upRightBtn = QtWidgets.QPushButton(self.motAutoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upRightBtn.sizePolicy().hasHeightForWidth())
        self.upRightBtn.setSizePolicy(sizePolicy)
        self.upRightBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.upRightBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.upRightBtn.setObjectName("upRightBtn")
        self.gridLayout_9.addWidget(self.upRightBtn, 0, 2, 1, 1)
        self.upLeftBtn = QtWidgets.QPushButton(self.motAutoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upLeftBtn.sizePolicy().hasHeightForWidth())
        self.upLeftBtn.setSizePolicy(sizePolicy)
        self.upLeftBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.upLeftBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.upLeftBtn.setObjectName("upLeftBtn")
        self.gridLayout_9.addWidget(self.upLeftBtn, 0, 0, 1, 1)
        self.downLeftBtn = QtWidgets.QPushButton(self.motAutoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.downLeftBtn.sizePolicy().hasHeightForWidth())
        self.downLeftBtn.setSizePolicy(sizePolicy)
        self.downLeftBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.downLeftBtn.setObjectName("downLeftBtn")
        self.gridLayout_9.addWidget(self.downLeftBtn, 2, 0, 1, 1)
        self.centerBtn = QtWidgets.QPushButton(self.motAutoTab)
        self.centerBtn.setMaximumSize(QtCore.QSize(16777215, 40))
        self.centerBtn.setObjectName("centerBtn")
        self.gridLayout_9.addWidget(self.centerBtn, 1, 1, 1, 1)
        self.stopXyBtn = QtWidgets.QPushButton(self.motAutoTab)
        self.stopXyBtn.setObjectName("stopXyBtn")
        self.gridLayout_9.addWidget(self.stopXyBtn, 2, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.motAutoTab)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_9.addWidget(self.label_42, 1, 0, 1, 1)
        self.findCenterBtn = QtWidgets.QPushButton(self.motAutoTab)
        self.findCenterBtn.setObjectName("findCenterBtn")
        self.gridLayout_9.addWidget(self.findCenterBtn, 0, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.motAutoTab)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_9.addWidget(self.label_43, 1, 2, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_44 = QtWidgets.QLabel(self.motAutoTab)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_8.addWidget(self.label_44)
        self.topBtn = QtWidgets.QPushButton(self.motAutoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topBtn.sizePolicy().hasHeightForWidth())
        self.topBtn.setSizePolicy(sizePolicy)
        self.topBtn.setMinimumSize(QtCore.QSize(85, 40))
        self.topBtn.setMaximumSize(QtCore.QSize(85, 40))
        self.topBtn.setObjectName("topBtn")
        self.verticalLayout_8.addWidget(self.topBtn)
        self.stopZBtn = QtWidgets.QPushButton(self.motAutoTab)
        self.stopZBtn.setObjectName("stopZBtn")
        self.verticalLayout_8.addWidget(self.stopZBtn)
        self.bottomBtn = QtWidgets.QPushButton(self.motAutoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottomBtn.sizePolicy().hasHeightForWidth())
        self.bottomBtn.setSizePolicy(sizePolicy)
        self.bottomBtn.setMinimumSize(QtCore.QSize(85, 40))
        self.bottomBtn.setMaximumSize(QtCore.QSize(40, 85))
        self.bottomBtn.setObjectName("bottomBtn")
        self.verticalLayout_8.addWidget(self.bottomBtn)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.horizontalLayout_7.setStretch(0, 4)
        self.horizontalLayout_7.setStretch(1, 1)
        self.motorTabs.addTab(self.motAutoTab, "")
        self.verticalLayout.addWidget(self.motorTabs)
        self.motorsDock.setWidget(self.dockWidgetContents_2)
        CoMPlEx_GUI.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.motorsDock)
        self.settingsDock = QtWidgets.QDockWidget(CoMPlEx_GUI)
        self.settingsDock.setMinimumSize(QtCore.QSize(406, 489))
        self.settingsDock.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.settingsDock.setAllowedAreas(QtCore.Qt.RightDockWidgetArea)
        self.settingsDock.setObjectName("settingsDock")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.functionsTabs = QtWidgets.QTabWidget(self.dockWidgetContents_3)
        self.functionsTabs.setIconSize(QtCore.QSize(32, 32))
        self.functionsTabs.setTabsClosable(False)
        self.functionsTabs.setObjectName("functionsTabs")
        self.fbTab = QtWidgets.QWidget()
        self.fbTab.setObjectName("fbTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.fbTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.uploadSetPtBtn = QtWidgets.QPushButton(self.fbTab)
        self.uploadSetPtBtn.setObjectName("uploadSetPtBtn")
        self.gridLayout_4.addWidget(self.uploadSetPtBtn, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.fbTab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.pGainNumDbl = QtWidgets.QDoubleSpinBox(self.fbTab)
        self.pGainNumDbl.setObjectName("pGainNumDbl")
        self.gridLayout_4.addWidget(self.pGainNumDbl, 2, 1, 1, 1)
        self.setPtNumDbl = QtWidgets.QDoubleSpinBox(self.fbTab)
        self.setPtNumDbl.setObjectName("setPtNumDbl")
        self.gridLayout_4.addWidget(self.setPtNumDbl, 1, 1, 1, 1)
        self.iGainNumDbl = QtWidgets.QDoubleSpinBox(self.fbTab)
        self.iGainNumDbl.setObjectName("iGainNumDbl")
        self.gridLayout_4.addWidget(self.iGainNumDbl, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.fbTab)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.uploadIGainBtn = QtWidgets.QPushButton(self.fbTab)
        self.uploadIGainBtn.setObjectName("uploadIGainBtn")
        self.gridLayout_4.addWidget(self.uploadIGainBtn, 3, 2, 1, 1)
        self.uploadPGainBtn = QtWidgets.QPushButton(self.fbTab)
        self.uploadPGainBtn.setObjectName("uploadPGainBtn")
        self.gridLayout_4.addWidget(self.uploadPGainBtn, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.fbTab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 3, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.fbTab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 4, 0, 1, 2)
        self.uploadFbBtn = QtWidgets.QPushButton(self.fbTab)
        self.uploadFbBtn.setObjectName("uploadFbBtn")
        self.gridLayout_4.addWidget(self.uploadFbBtn, 4, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 5, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 0, 0, 1, 1)
        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(1, 1)
        self.gridLayout_4.setRowStretch(2, 1)
        self.gridLayout_4.setRowStretch(3, 1)
        self.gridLayout_4.setRowStretch(4, 1)
        self.gridLayout_4.setRowStretch(5, 20)
        self.functionsTabs.addTab(self.fbTab, "")
        self.calibQpdTab = QtWidgets.QWidget()
        self.calibQpdTab.setObjectName("calibQpdTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.calibQpdTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.uploadCalibStimFreqBtn = QtWidgets.QPushButton(self.calibQpdTab)
        self.uploadCalibStimFreqBtn.setObjectName("uploadCalibStimFreqBtn")
        self.gridLayout_5.addWidget(self.uploadCalibStimFreqBtn, 5, 2, 1, 1)
        self.calibStimFreqNumDbl = QtWidgets.QDoubleSpinBox(self.calibQpdTab)
        self.calibStimFreqNumDbl.setObjectName("calibStimFreqNumDbl")
        self.gridLayout_5.addWidget(self.calibStimFreqNumDbl, 5, 1, 1, 1)
        self.calibStimZOffsetNumDbl = QtWidgets.QDoubleSpinBox(self.calibQpdTab)
        self.calibStimZOffsetNumDbl.setObjectName("calibStimZOffsetNumDbl")
        self.gridLayout_5.addWidget(self.calibStimZOffsetNumDbl, 3, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.calibQpdTab)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_5.addWidget(self.line_4, 2, 0, 1, 3)
        self.kdNumDbl = QtWidgets.QDoubleSpinBox(self.calibQpdTab)
        self.kdNumDbl.setMinimum(1.0)
        self.kdNumDbl.setMaximum(1000.0)
        self.kdNumDbl.setProperty("value", 1.0)
        self.kdNumDbl.setObjectName("kdNumDbl")
        self.gridLayout_5.addWidget(self.kdNumDbl, 1, 1, 1, 1)
        self.uploadKdBtn = QtWidgets.QPushButton(self.calibQpdTab)
        self.uploadKdBtn.setObjectName("uploadKdBtn")
        self.gridLayout_5.addWidget(self.uploadKdBtn, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.calibQpdTab)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 5, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.calibQpdTab)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.calibQpdTab)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 3, 0, 1, 1)
        self.uploadCalibStimZOffsetBtn = QtWidgets.QPushButton(self.calibQpdTab)
        self.uploadCalibStimZOffsetBtn.setObjectName("uploadCalibStimZOffsetBtn")
        self.gridLayout_5.addWidget(self.uploadCalibStimZOffsetBtn, 3, 2, 1, 1)
        self.uploadCalibStimAmplBtn = QtWidgets.QPushButton(self.calibQpdTab)
        self.uploadCalibStimAmplBtn.setObjectName("uploadCalibStimAmplBtn")
        self.gridLayout_5.addWidget(self.uploadCalibStimAmplBtn, 4, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.calibQpdTab)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 1)
        self.calibStimAmplNumDbl = QtWidgets.QDoubleSpinBox(self.calibQpdTab)
        self.calibStimAmplNumDbl.setObjectName("calibStimAmplNumDbl")
        self.gridLayout_5.addWidget(self.calibStimAmplNumDbl, 4, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.calibQpdTab)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_5.addWidget(self.line_5, 6, 0, 1, 2)
        self.uploadCalibStimBtn = QtWidgets.QPushButton(self.calibQpdTab)
        self.uploadCalibStimBtn.setObjectName("uploadCalibStimBtn")
        self.gridLayout_5.addWidget(self.uploadCalibStimBtn, 6, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 7, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem5, 0, 0, 1, 1)
        self.gridLayout_5.setRowStretch(0, 1)
        self.gridLayout_5.setRowStretch(1, 1)
        self.gridLayout_5.setRowStretch(2, 1)
        self.gridLayout_5.setRowStretch(3, 1)
        self.gridLayout_5.setRowStretch(4, 1)
        self.gridLayout_5.setRowStretch(5, 1)
        self.gridLayout_5.setRowStretch(6, 1)
        self.gridLayout_5.setRowStretch(7, 20)
        self.functionsTabs.addTab(self.calibQpdTab, "")
        self.calibKTab = QtWidgets.QWidget()
        self.calibKTab.setObjectName("calibKTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.calibKTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_17 = QtWidgets.QLabel(self.calibKTab)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 4, 0, 1, 1)
        self.uploadClWidBtn = QtWidgets.QPushButton(self.calibKTab)
        self.uploadClWidBtn.setObjectName("uploadClWidBtn")
        self.gridLayout_6.addWidget(self.uploadClWidBtn, 5, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.calibKTab)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.calibKTab)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 5, 0, 1, 1)
        self.uploadPkStartFreqBtn = QtWidgets.QPushButton(self.calibKTab)
        self.uploadPkStartFreqBtn.setObjectName("uploadPkStartFreqBtn")
        self.gridLayout_6.addWidget(self.uploadPkStartFreqBtn, 2, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.calibKTab)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 7, 0, 1, 1)
        self.clLenNumDbl = QtWidgets.QDoubleSpinBox(self.calibKTab)
        self.clLenNumDbl.setObjectName("clLenNumDbl")
        self.gridLayout_6.addWidget(self.clLenNumDbl, 4, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.calibKTab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 0, 0, 1, 1)
        self.uploadClLenBtn = QtWidgets.QPushButton(self.calibKTab)
        self.uploadClLenBtn.setObjectName("uploadClLenBtn")
        self.gridLayout_6.addWidget(self.uploadClLenBtn, 4, 2, 1, 1)
        self.uploadKBtn = QtWidgets.QPushButton(self.calibKTab)
        self.uploadKBtn.setObjectName("uploadKBtn")
        self.gridLayout_6.addWidget(self.uploadKBtn, 0, 2, 1, 1)
        self.uploadMediumDensBtn = QtWidgets.QPushButton(self.calibKTab)
        self.uploadMediumDensBtn.setObjectName("uploadMediumDensBtn")
        self.gridLayout_6.addWidget(self.uploadMediumDensBtn, 6, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.calibKTab)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 2, 0, 1, 1)
        self.mediumViscNumDbl = QtWidgets.QDoubleSpinBox(self.calibKTab)
        self.mediumViscNumDbl.setObjectName("mediumViscNumDbl")
        self.gridLayout_6.addWidget(self.mediumViscNumDbl, 7, 1, 1, 1)
        self.uploadMediumViscBtn = QtWidgets.QPushButton(self.calibKTab)
        self.uploadMediumViscBtn.setObjectName("uploadMediumViscBtn")
        self.gridLayout_6.addWidget(self.uploadMediumViscBtn, 7, 2, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.calibKTab)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_6.addWidget(self.line_6, 1, 0, 1, 3)
        self.pkEndFreqNumDbl = QtWidgets.QDoubleSpinBox(self.calibKTab)
        self.pkEndFreqNumDbl.setObjectName("pkEndFreqNumDbl")
        self.gridLayout_6.addWidget(self.pkEndFreqNumDbl, 3, 1, 1, 1)
        self.uploadPkEndFreqBtn = QtWidgets.QPushButton(self.calibKTab)
        self.uploadPkEndFreqBtn.setObjectName("uploadPkEndFreqBtn")
        self.gridLayout_6.addWidget(self.uploadPkEndFreqBtn, 3, 2, 1, 1)
        self.mediumDensNumDbl = QtWidgets.QDoubleSpinBox(self.calibKTab)
        self.mediumDensNumDbl.setObjectName("mediumDensNumDbl")
        self.gridLayout_6.addWidget(self.mediumDensNumDbl, 6, 1, 1, 1)
        self.pkStartFreqNumDbl = QtWidgets.QDoubleSpinBox(self.calibKTab)
        self.pkStartFreqNumDbl.setObjectName("pkStartFreqNumDbl")
        self.gridLayout_6.addWidget(self.pkStartFreqNumDbl, 2, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.calibKTab)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 6, 0, 1, 1)
        self.clWidNumDbl = QtWidgets.QDoubleSpinBox(self.calibKTab)
        self.clWidNumDbl.setObjectName("clWidNumDbl")
        self.gridLayout_6.addWidget(self.clWidNumDbl, 5, 1, 1, 1)
        self.kNumDbl = QtWidgets.QDoubleSpinBox(self.calibKTab)
        self.kNumDbl.setMinimum(1.0)
        self.kNumDbl.setMaximum(1000.0)
        self.kNumDbl.setObjectName("kNumDbl")
        self.gridLayout_6.addWidget(self.kNumDbl, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.calibKTab)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 9, 0, 1, 1)
        self.avgNumNum = QtWidgets.QSpinBox(self.calibKTab)
        self.avgNumNum.setObjectName("avgNumNum")
        self.gridLayout_6.addWidget(self.avgNumNum, 9, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.calibKTab)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_6.addWidget(self.line_7, 8, 0, 1, 2)
        self.uploadKCalibBtn = QtWidgets.QPushButton(self.calibKTab)
        self.uploadKCalibBtn.setObjectName("uploadKCalibBtn")
        self.gridLayout_6.addWidget(self.uploadKCalibBtn, 8, 2, 1, 1)
        self.functionsTabs.addTab(self.calibKTab, "")
        self.fvsdTab = QtWidgets.QWidget()
        self.fvsdTab.setObjectName("fvsdTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.fvsdTab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_26 = QtWidgets.QLabel(self.fvsdTab)
        self.label_26.setObjectName("label_26")
        self.gridLayout_7.addWidget(self.label_26, 4, 0, 1, 1)
        self.endZNumDbl = QtWidgets.QDoubleSpinBox(self.fvsdTab)
        self.endZNumDbl.setKeyboardTracking(False)
        self.endZNumDbl.setObjectName("endZNumDbl")
        self.gridLayout_7.addWidget(self.endZNumDbl, 2, 1, 1, 1)
        self.holdTimeNumDbl = QtWidgets.QDoubleSpinBox(self.fvsdTab)
        self.holdTimeNumDbl.setObjectName("holdTimeNumDbl")
        self.gridLayout_7.addWidget(self.holdTimeNumDbl, 5, 1, 1, 1)
        self.uploadFvsdBtn = QtWidgets.QPushButton(self.fvsdTab)
        self.uploadFvsdBtn.setObjectName("uploadFvsdBtn")
        self.gridLayout_7.addWidget(self.uploadFvsdBtn, 6, 2, 1, 1)
        self.uploadStartZBtn = QtWidgets.QPushButton(self.fvsdTab)
        self.uploadStartZBtn.setObjectName("uploadStartZBtn")
        self.gridLayout_7.addWidget(self.uploadStartZBtn, 1, 2, 1, 1)
        self.uploadRetrSpeedBtn = QtWidgets.QPushButton(self.fvsdTab)
        self.uploadRetrSpeedBtn.setObjectName("uploadRetrSpeedBtn")
        self.gridLayout_7.addWidget(self.uploadRetrSpeedBtn, 4, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.fvsdTab)
        self.label_24.setObjectName("label_24")
        self.gridLayout_7.addWidget(self.label_24, 2, 0, 1, 1)
        self.maxFNumDbl = QtWidgets.QDoubleSpinBox(self.fvsdTab)
        self.maxFNumDbl.setObjectName("maxFNumDbl")
        self.gridLayout_7.addWidget(self.maxFNumDbl, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.fvsdTab)
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 1, 0, 1, 1)
        self.uploadAppSpeedBtn = QtWidgets.QPushButton(self.fvsdTab)
        self.uploadAppSpeedBtn.setObjectName("uploadAppSpeedBtn")
        self.gridLayout_7.addWidget(self.uploadAppSpeedBtn, 3, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.fvsdTab)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.fvsdTab)
        self.label_27.setObjectName("label_27")
        self.gridLayout_7.addWidget(self.label_27, 5, 0, 1, 1)
        self.uploadHoldTimeBtn = QtWidgets.QPushButton(self.fvsdTab)
        self.uploadHoldTimeBtn.setObjectName("uploadHoldTimeBtn")
        self.gridLayout_7.addWidget(self.uploadHoldTimeBtn, 5, 2, 1, 1)
        self.constForceCkBox = QtWidgets.QCheckBox(self.fvsdTab)
        self.constForceCkBox.setObjectName("constForceCkBox")
        self.gridLayout_7.addWidget(self.constForceCkBox, 7, 0, 1, 1)
        self.startZNumDbl = QtWidgets.QDoubleSpinBox(self.fvsdTab)
        self.startZNumDbl.setKeyboardTracking(False)
        self.startZNumDbl.setObjectName("startZNumDbl")
        self.gridLayout_7.addWidget(self.startZNumDbl, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.fvsdTab)
        self.label_25.setObjectName("label_25")
        self.gridLayout_7.addWidget(self.label_25, 3, 0, 1, 1)
        self.uploadEndZBtn = QtWidgets.QPushButton(self.fvsdTab)
        self.uploadEndZBtn.setObjectName("uploadEndZBtn")
        self.gridLayout_7.addWidget(self.uploadEndZBtn, 2, 2, 1, 1)
        self.appSpeedNumDbl = QtWidgets.QDoubleSpinBox(self.fvsdTab)
        self.appSpeedNumDbl.setKeyboardTracking(False)
        self.appSpeedNumDbl.setObjectName("appSpeedNumDbl")
        self.gridLayout_7.addWidget(self.appSpeedNumDbl, 3, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.fvsdTab)
        self.label_28.setObjectName("label_28")
        self.gridLayout_7.addWidget(self.label_28, 8, 0, 1, 1)
        self.uploadMaxFBtn = QtWidgets.QPushButton(self.fvsdTab)
        self.uploadMaxFBtn.setObjectName("uploadMaxFBtn")
        self.gridLayout_7.addWidget(self.uploadMaxFBtn, 0, 2, 1, 1)
        self.retrSpeedNumDbl = QtWidgets.QDoubleSpinBox(self.fvsdTab)
        self.retrSpeedNumDbl.setKeyboardTracking(False)
        self.retrSpeedNumDbl.setObjectName("retrSpeedNumDbl")
        self.gridLayout_7.addWidget(self.retrSpeedNumDbl, 4, 1, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.fvsdTab)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_7.addWidget(self.line_8, 6, 0, 1, 2)
        self.curveNumNum = QtWidgets.QSpinBox(self.fvsdTab)
        self.curveNumNum.setObjectName("curveNumNum")
        self.gridLayout_7.addWidget(self.curveNumNum, 8, 1, 1, 1)
        self.functionsTabs.addTab(self.fvsdTab, "")
        self.custFvsdTab = QtWidgets.QWidget()
        self.custFvsdTab.setEnabled(True)
        self.custFvsdTab.setObjectName("custFvsdTab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.custFvsdTab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.segCmbBox = QtWidgets.QComboBox(self.custFvsdTab)
        self.segCmbBox.setObjectName("segCmbBox")
        self.gridLayout_8.addWidget(self.segCmbBox, 8, 0, 1, 2)
        self.removeSegBtn = QtWidgets.QPushButton(self.custFvsdTab)
        self.removeSegBtn.setObjectName("removeSegBtn")
        self.gridLayout_8.addWidget(self.removeSegBtn, 8, 3, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.custFvsdTab)
        self.label_31.setObjectName("label_31")
        self.gridLayout_8.addWidget(self.label_31, 4, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.custFvsdTab)
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 3, 0, 1, 1)
        self.holdTimecNumDbl = QtWidgets.QDoubleSpinBox(self.custFvsdTab)
        self.holdTimecNumDbl.setEnabled(False)
        self.holdTimecNumDbl.setObjectName("holdTimecNumDbl")
        self.gridLayout_8.addWidget(self.holdTimecNumDbl, 6, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.custFvsdTab)
        self.label_29.setObjectName("label_29")
        self.gridLayout_8.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.custFvsdTab)
        self.label_45.setObjectName("label_45")
        self.gridLayout_8.addWidget(self.label_45, 10, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.custFvsdTab)
        self.label_35.setObjectName("label_35")
        self.gridLayout_8.addWidget(self.label_35, 6, 0, 1, 1)
        self.uploadStartZcBtn = QtWidgets.QPushButton(self.custFvsdTab)
        self.uploadStartZcBtn.setObjectName("uploadStartZcBtn")
        self.gridLayout_8.addWidget(self.uploadStartZcBtn, 0, 3, 1, 1)
        self.endFcNumDbl = QtWidgets.QDoubleSpinBox(self.custFvsdTab)
        self.endFcNumDbl.setObjectName("endFcNumDbl")
        self.gridLayout_8.addWidget(self.endFcNumDbl, 4, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.custFvsdTab)
        self.label_46.setObjectName("label_46")
        self.gridLayout_8.addWidget(self.label_46, 5, 0, 1, 1)
        self.curveNumcNum = QtWidgets.QSpinBox(self.custFvsdTab)
        self.curveNumcNum.setObjectName("curveNumcNum")
        self.gridLayout_8.addWidget(self.curveNumcNum, 10, 1, 1, 1)
        self.showZTravelBtn = QtWidgets.QPushButton(self.custFvsdTab)
        self.showZTravelBtn.setObjectName("showZTravelBtn")
        self.gridLayout_8.addWidget(self.showZTravelBtn, 9, 0, 1, 4)
        self.updateSegBtn = QtWidgets.QPushButton(self.custFvsdTab)
        self.updateSegBtn.setObjectName("updateSegBtn")
        self.gridLayout_8.addWidget(self.updateSegBtn, 8, 2, 1, 1)
        self.endZcNumDbl = QtWidgets.QDoubleSpinBox(self.custFvsdTab)
        self.endZcNumDbl.setKeyboardTracking(False)
        self.endZcNumDbl.setObjectName("endZcNumDbl")
        self.gridLayout_8.addWidget(self.endZcNumDbl, 3, 1, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.custFvsdTab)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_8.addWidget(self.line_9, 1, 0, 1, 4)
        self.speedcNumDbl = QtWidgets.QDoubleSpinBox(self.custFvsdTab)
        self.speedcNumDbl.setEnabled(True)
        self.speedcNumDbl.setKeyboardTracking(False)
        self.speedcNumDbl.setObjectName("speedcNumDbl")
        self.gridLayout_8.addWidget(self.speedcNumDbl, 5, 1, 1, 1)
        self.startZcNumDbl = QtWidgets.QDoubleSpinBox(self.custFvsdTab)
        self.startZcNumDbl.setObjectName("startZcNumDbl")
        self.gridLayout_8.addWidget(self.startZcNumDbl, 0, 1, 1, 1)
        self.altZSegBtn = QtWidgets.QPushButton(self.custFvsdTab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/altZ.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.altZSegBtn.setIcon(icon)
        self.altZSegBtn.setIconSize(QtCore.QSize(20, 20))
        self.altZSegBtn.setCheckable(False)
        self.altZSegBtn.setDefault(False)
        self.altZSegBtn.setObjectName("altZSegBtn")
        self.gridLayout_8.addWidget(self.altZSegBtn, 2, 0, 1, 1)
        self.altFSegBtn = QtWidgets.QPushButton(self.custFvsdTab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/altF.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.altFSegBtn.setIcon(icon1)
        self.altFSegBtn.setIconSize(QtCore.QSize(20, 20))
        self.altFSegBtn.setCheckable(False)
        self.altFSegBtn.setObjectName("altFSegBtn")
        self.gridLayout_8.addWidget(self.altFSegBtn, 2, 1, 1, 1)
        self.farSegBtn = QtWidgets.QPushButton(self.custFvsdTab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/far.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.farSegBtn.setIcon(icon2)
        self.farSegBtn.setIconSize(QtCore.QSize(20, 20))
        self.farSegBtn.setCheckable(False)
        self.farSegBtn.setObjectName("farSegBtn")
        self.gridLayout_8.addWidget(self.farSegBtn, 2, 2, 1, 1)
        self.nearSegBtn = QtWidgets.QPushButton(self.custFvsdTab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/near.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nearSegBtn.setIcon(icon3)
        self.nearSegBtn.setIconSize(QtCore.QSize(20, 20))
        self.nearSegBtn.setCheckable(False)
        self.nearSegBtn.setChecked(False)
        self.nearSegBtn.setObjectName("nearSegBtn")
        self.gridLayout_8.addWidget(self.nearSegBtn, 2, 3, 1, 1)
        self.addSegBtn = QtWidgets.QPushButton(self.custFvsdTab)
        self.addSegBtn.setObjectName("addSegBtn")
        self.gridLayout_8.addWidget(self.addSegBtn, 7, 0, 1, 2)
        self.functionsTabs.addTab(self.custFvsdTab, "")
        self.motorTab = QtWidgets.QWidget()
        self.motorTab.setObjectName("motorTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.motorTab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.motorTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.label_39 = QtWidgets.QLabel(self.groupBox_2)
        self.label_39.setObjectName("label_39")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.xStepNumNum = QtWidgets.QSpinBox(self.groupBox_2)
        self.xStepNumNum.setMaximum(2000)
        self.xStepNumNum.setObjectName("xStepNumNum")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.xStepNumNum)
        self.label_40 = QtWidgets.QLabel(self.groupBox_2)
        self.label_40.setObjectName("label_40")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.yStepNumNum = QtWidgets.QSpinBox(self.groupBox_2)
        self.yStepNumNum.setMaximum(2000)
        self.yStepNumNum.setObjectName("yStepNumNum")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.yStepNumNum)
        self.label_41 = QtWidgets.QLabel(self.groupBox_2)
        self.label_41.setObjectName("label_41")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.zStepNumNum = QtWidgets.QSpinBox(self.groupBox_2)
        self.zStepNumNum.setObjectName("zStepNumNum")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.zStepNumNum)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.motorTab)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_36 = QtWidgets.QLabel(self.groupBox)
        self.label_36.setObjectName("label_36")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.xStepNumMapNum = QtWidgets.QSpinBox(self.groupBox)
        self.xStepNumMapNum.setMaximum(2000)
        self.xStepNumMapNum.setObjectName("xStepNumMapNum")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.xStepNumMapNum)
        self.label_37 = QtWidgets.QLabel(self.groupBox)
        self.label_37.setObjectName("label_37")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.yStepNumMapNum = QtWidgets.QSpinBox(self.groupBox)
        self.yStepNumMapNum.setMaximum(2000)
        self.yStepNumMapNum.setObjectName("yStepNumMapNum")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.yStepNumMapNum)
        self.label_38 = QtWidgets.QLabel(self.groupBox)
        self.label_38.setObjectName("label_38")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.ptNumMapNum = QtWidgets.QSpinBox(self.groupBox)
        self.ptNumMapNum.setMaximum(10000)
        self.ptNumMapNum.setObjectName("ptNumMapNum")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ptNumMapNum)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.functionsTabs.addTab(self.motorTab, "")
        self.saveTab = QtWidgets.QWidget()
        self.saveTab.setObjectName("saveTab")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.saveTab)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.fileNameRootLine = QtWidgets.QLineEdit(self.saveTab)
        self.fileNameRootLine.setObjectName("fileNameRootLine")
        self.gridLayout_10.addWidget(self.fileNameRootLine, 1, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.saveTab)
        self.label_48.setObjectName("label_48")
        self.gridLayout_10.addWidget(self.label_48, 2, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.saveTab)
        self.label_47.setObjectName("label_47")
        self.gridLayout_10.addWidget(self.label_47, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem6, 3, 0, 1, 1)
        self.dirLine = QtWidgets.QLineEdit(self.saveTab)
        self.dirLine.setObjectName("dirLine")
        self.gridLayout_10.addWidget(self.dirLine, 2, 1, 1, 1)
        self.browseBtn = QtWidgets.QPushButton(self.saveTab)
        self.browseBtn.setObjectName("browseBtn")
        self.gridLayout_10.addWidget(self.browseBtn, 2, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem7, 0, 1, 1, 1)
        self.gridLayout_10.setRowStretch(0, 1)
        self.gridLayout_10.setRowStretch(1, 1)
        self.gridLayout_10.setRowStretch(2, 1)
        self.gridLayout_10.setRowStretch(3, 20)
        self.functionsTabs.addTab(self.saveTab, "")
        self.verticalLayout_4.addWidget(self.functionsTabs)
        self.settingsDock.setWidget(self.dockWidgetContents_3)
        CoMPlEx_GUI.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.settingsDock)
        self.remoteDock = QtWidgets.QDockWidget(CoMPlEx_GUI)
        self.remoteDock.setMinimumSize(QtCore.QSize(251, 130))
        self.remoteDock.setMaximumSize(QtCore.QSize(524287, 130))
        self.remoteDock.setObjectName("remoteDock")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.channelCmbBox = QtWidgets.QComboBox(self.dockWidgetContents_4)
        self.channelCmbBox.setObjectName("channelCmbBox")
        self.channelCmbBox.addItem("")
        self.channelCmbBox.addItem("")
        self.channelCmbBox.addItem("")
        self.channelCmbBox.addItem("")
        self.channelCmbBox.addItem("")
        self.channelCmbBox.addItem("")
        self.channelCmbBox.addItem("")
        self.horizontalLayout_6.addWidget(self.channelCmbBox)
        self.rdsLine = QtWidgets.QLineEdit(self.dockWidgetContents_4)
        self.rdsLine.setReadOnly(True)
        self.rdsLine.setObjectName("rdsLine")
        self.horizontalLayout_6.addWidget(self.rdsLine)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.playBtn = QtWidgets.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playBtn.sizePolicy().hasHeightForWidth())
        self.playBtn.setSizePolicy(sizePolicy)
        self.playBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.playBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.playBtn.setObjectName("playBtn")
        self.horizontalLayout_5.addWidget(self.playBtn)
        self.stopBtn = QtWidgets.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopBtn.sizePolicy().hasHeightForWidth())
        self.stopBtn.setSizePolicy(sizePolicy)
        self.stopBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.stopBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout_5.addWidget(self.stopBtn)
        self.remoteProg = QtWidgets.QProgressBar(self.dockWidgetContents_4)
        self.remoteProg.setProperty("value", 0)
        self.remoteProg.setObjectName("remoteProg")
        self.horizontalLayout_5.addWidget(self.remoteProg)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.remoteDock.setWidget(self.dockWidgetContents_4)
        CoMPlEx_GUI.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.remoteDock)
        self.action_Set_save_paths = QtWidgets.QAction(CoMPlEx_GUI)
        self.action_Set_save_paths.setObjectName("action_Set_save_paths")
        self.action_QPD_and_piezo = QtWidgets.QAction(CoMPlEx_GUI)
        self.action_QPD_and_piezo.setCheckable(True)
        self.action_QPD_and_piezo.setChecked(True)
        self.action_QPD_and_piezo.setObjectName("action_QPD_and_piezo")
        self.action_Motors = QtWidgets.QAction(CoMPlEx_GUI)
        self.action_Motors.setCheckable(True)
        self.action_Motors.setChecked(True)
        self.action_Motors.setObjectName("action_Motors")
        self.action_General_config = QtWidgets.QAction(CoMPlEx_GUI)
        self.action_General_config.setObjectName("action_General_config")
        self.action_Controls_config = QtWidgets.QAction(CoMPlEx_GUI)
        self.action_Controls_config.setObjectName("action_Controls_config")
        self.action_Settings = QtWidgets.QAction(CoMPlEx_GUI)
        self.action_Settings.setCheckable(True)
        self.action_Settings.setChecked(True)
        self.action_Settings.setObjectName("action_Settings")
        self.action_Remote = QtWidgets.QAction(CoMPlEx_GUI)
        self.action_Remote.setCheckable(True)
        self.action_Remote.setChecked(True)
        self.action_Remote.setObjectName("action_Remote")
        self.action_Save_parameters = QtWidgets.QAction(CoMPlEx_GUI)
        self.action_Save_parameters.setObjectName("action_Save_parameters")
        self.action_Load_parameters = QtWidgets.QAction(CoMPlEx_GUI)
        self.action_Load_parameters.setObjectName("action_Load_parameters")
        self.action_Exit = QtWidgets.QAction(CoMPlEx_GUI)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Edit_config = QtWidgets.QAction(CoMPlEx_GUI)
        self.action_Edit_config.setObjectName("action_Edit_config")
        self.action_Open_SiMPlE = QtWidgets.QAction(CoMPlEx_GUI)
        self.action_Open_SiMPlE.setObjectName("action_Open_SiMPlE")
        self.menu_Config.addAction(self.action_Save_parameters)
        self.menu_Config.addAction(self.action_Load_parameters)
        self.menu_Config.addAction(self.action_Edit_config)
        self.menu_Config.addAction(self.action_Exit)
        self.menu_View.addAction(self.action_QPD_and_piezo)
        self.menu_View.addAction(self.action_Motors)
        self.menu_View.addAction(self.action_Settings)
        self.menu_View.addAction(self.action_Remote)
        self.menu_Analysis.addAction(self.action_Open_SiMPlE)
        self.menubar.addAction(self.menu_Config.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Analysis.menuAction())

        self.retranslateUi(CoMPlEx_GUI)
        self.motorTabs.setCurrentIndex(0)
        self.functionsTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CoMPlEx_GUI)

    def retranslateUi(self, CoMPlEx_GUI):
        _translate = QtCore.QCoreApplication.translate
        CoMPlEx_GUI.setWindowTitle(_translate("CoMPlEx_GUI", "MainWindow"))
        self.menu_Config.setTitle(_translate("CoMPlEx_GUI", "&File"))
        self.menu_View.setTitle(_translate("CoMPlEx_GUI", "&View"))
        self.menu_Analysis.setTitle(_translate("CoMPlEx_GUI", "&Analysis"))
        self.qpdNpiezoDock.setWindowTitle(_translate("CoMPlEx_GUI", "QPD and piezo monitor"))
        self.label_3.setText(_translate("CoMPlEx_GUI", "Sum [V]"))
        self.label.setText(_translate("CoMPlEx_GUI", "Deflection [V]"))
        self.label_2.setText(_translate("CoMPlEx_GUI", "Torsion [V]"))
        self.label_4.setText(_translate("CoMPlEx_GUI", "Z [um]"))
        self.motorsDock.setWindowTitle(_translate("CoMPlEx_GUI", "Motors"))
        self.yPlusBtn.setText(_translate("CoMPlEx_GUI", "△"))
        self.xMinusBtn.setText(_translate("CoMPlEx_GUI", "◁"))
        self.xPlusBtn.setText(_translate("CoMPlEx_GUI", "▷"))
        self.yMinusBtn.setText(_translate("CoMPlEx_GUI", "▽"))
        self.label_5.setText(_translate("CoMPlEx_GUI", "XY"))
        self.goCenterBtn.setText(_translate("CoMPlEx_GUI", "0"))
        self.zPlusBtn.setText(_translate("CoMPlEx_GUI", "△"))
        self.label_6.setText(_translate("CoMPlEx_GUI", "z"))
        self.zMinusBtn.setText(_translate("CoMPlEx_GUI", "▽"))
        self.resetXYBtn.setText(_translate("CoMPlEx_GUI", "Reset XY"))
        self.resetZBtn.setText(_translate("CoMPlEx_GUI", "Reset Z"))
        self.motorTabs.setTabText(self.motorTabs.indexOf(self.motManTab), _translate("CoMPlEx_GUI", "Manual"))
        self.downRightBtn.setText(_translate("CoMPlEx_GUI", "◿"))
        self.upRightBtn.setText(_translate("CoMPlEx_GUI", "◹"))
        self.upLeftBtn.setText(_translate("CoMPlEx_GUI", "◸"))
        self.downLeftBtn.setText(_translate("CoMPlEx_GUI", "◺"))
        self.centerBtn.setText(_translate("CoMPlEx_GUI", "⊕"))
        self.stopXyBtn.setText(_translate("CoMPlEx_GUI", "STOP"))
        self.label_42.setText(_translate("CoMPlEx_GUI", "XY"))
        self.findCenterBtn.setText(_translate("CoMPlEx_GUI", "Find center"))
        self.label_43.setText(_translate("CoMPlEx_GUI", "XY"))
        self.label_44.setText(_translate("CoMPlEx_GUI", "Z"))
        self.topBtn.setText(_translate("CoMPlEx_GUI", "⊤"))
        self.stopZBtn.setText(_translate("CoMPlEx_GUI", "STOP"))
        self.bottomBtn.setText(_translate("CoMPlEx_GUI", "⊥"))
        self.motorTabs.setTabText(self.motorTabs.indexOf(self.motAutoTab), _translate("CoMPlEx_GUI", "Auto"))
        self.settingsDock.setWindowTitle(_translate("CoMPlEx_GUI", "Settings"))
        self.uploadSetPtBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.label_7.setText(_translate("CoMPlEx_GUI", "Set Point [V]"))
        self.label_8.setText(_translate("CoMPlEx_GUI", "P Gain"))
        self.uploadIGainBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.uploadPGainBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.label_9.setText(_translate("CoMPlEx_GUI", "I Gain"))
        self.uploadFbBtn.setText(_translate("CoMPlEx_GUI", "Upload All"))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.fbTab), _translate("CoMPlEx_GUI", "Feedback"))
        self.uploadCalibStimFreqBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.uploadKdBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.label_13.setText(_translate("CoMPlEx_GUI", "Frequency [Hz]"))
        self.label_12.setText(_translate("CoMPlEx_GUI", "Amplitude [nm]"))
        self.label_11.setText(_translate("CoMPlEx_GUI", "Z offset [nm]"))
        self.uploadCalibStimZOffsetBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.uploadCalibStimAmplBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.label_10.setText(_translate("CoMPlEx_GUI", "Kd [nm/V]"))
        self.uploadCalibStimBtn.setText(_translate("CoMPlEx_GUI", "Upload All"))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.calibQpdTab), _translate("CoMPlEx_GUI", "QPD Calibration"))
        self.label_17.setText(_translate("CoMPlEx_GUI", "Cant. Length [nm]"))
        self.uploadClWidBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.label_16.setText(_translate("CoMPlEx_GUI", "Peak end freq[Hz]"))
        self.label_18.setText(_translate("CoMPlEx_GUI", "Cant. Width [nm]"))
        self.uploadPkStartFreqBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.label_20.setText(_translate("CoMPlEx_GUI", "Medium visc. [nm]"))
        self.label_14.setText(_translate("CoMPlEx_GUI", "K [pN/nm]"))
        self.uploadClLenBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.uploadKBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.uploadMediumDensBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.label_15.setText(_translate("CoMPlEx_GUI", "Peak start freq[Hz]"))
        self.uploadMediumViscBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.uploadPkEndFreqBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.label_19.setText(_translate("CoMPlEx_GUI", "Medium dens. [nm]"))
        self.label_21.setText(_translate("CoMPlEx_GUI", "Average Num"))
        self.uploadKCalibBtn.setText(_translate("CoMPlEx_GUI", "Upload All"))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.calibKTab), _translate("CoMPlEx_GUI", "K Calibration"))
        self.label_26.setText(_translate("CoMPlEx_GUI", "Retr. speed [nm/s]"))
        self.uploadFvsdBtn.setText(_translate("CoMPlEx_GUI", "Upload All"))
        self.uploadStartZBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.uploadRetrSpeedBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.label_24.setText(_translate("CoMPlEx_GUI", "End Z [nm]"))
        self.label_23.setText(_translate("CoMPlEx_GUI", "Start Z [nm]"))
        self.uploadAppSpeedBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.label_22.setText(_translate("CoMPlEx_GUI", "Max Force [pN]"))
        self.label_27.setText(_translate("CoMPlEx_GUI", "Hold time [s]"))
        self.uploadHoldTimeBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.constForceCkBox.setText(_translate("CoMPlEx_GUI", "Constant Force"))
        self.label_25.setText(_translate("CoMPlEx_GUI", "App. speed [nm/s]"))
        self.uploadEndZBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.label_28.setText(_translate("CoMPlEx_GUI", "Curves number"))
        self.uploadMaxFBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.fvsdTab), _translate("CoMPlEx_GUI", "FvsD"))
        self.removeSegBtn.setText(_translate("CoMPlEx_GUI", "Remove"))
        self.label_31.setText(_translate("CoMPlEx_GUI", "Force step [pN]"))
        self.label_30.setText(_translate("CoMPlEx_GUI", "Z step [nm]"))
        self.label_29.setText(_translate("CoMPlEx_GUI", "Start Z [nm]"))
        self.label_45.setText(_translate("CoMPlEx_GUI", "Curves number"))
        self.label_35.setText(_translate("CoMPlEx_GUI", "Hold Time [s]"))
        self.uploadStartZcBtn.setText(_translate("CoMPlEx_GUI", "Upload"))
        self.label_46.setText(_translate("CoMPlEx_GUI", "Speed [nm/s]"))
        self.showZTravelBtn.setText(_translate("CoMPlEx_GUI", "Show Z travel preview"))
        self.updateSegBtn.setText(_translate("CoMPlEx_GUI", "Update"))
        self.altZSegBtn.setText(_translate("CoMPlEx_GUI", "Hold Z"))
        self.altFSegBtn.setText(_translate("CoMPlEx_GUI", "Hold F"))
        self.farSegBtn.setText(_translate("CoMPlEx_GUI", "Far"))
        self.nearSegBtn.setText(_translate("CoMPlEx_GUI", "Near"))
        self.addSegBtn.setText(_translate("CoMPlEx_GUI", "ADD"))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.custFvsdTab), _translate("CoMPlEx_GUI", "Custom FvsD"))
        self.groupBox_2.setTitle(_translate("CoMPlEx_GUI", "Manual movement"))
        self.label_39.setText(_translate("CoMPlEx_GUI", "X steps number"))
        self.label_40.setText(_translate("CoMPlEx_GUI", "Y steps number"))
        self.label_41.setText(_translate("CoMPlEx_GUI", "Z steps number"))
        self.groupBox.setTitle(_translate("CoMPlEx_GUI", "Map"))
        self.label_36.setText(_translate("CoMPlEx_GUI", "X steps number"))
        self.label_37.setText(_translate("CoMPlEx_GUI", "Y steps number"))
        self.label_38.setText(_translate("CoMPlEx_GUI", "Points number"))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.motorTab), _translate("CoMPlEx_GUI", "Motors"))
        self.label_48.setText(_translate("CoMPlEx_GUI", "Directory"))
        self.label_47.setText(_translate("CoMPlEx_GUI", "File Name root"))
        self.browseBtn.setText(_translate("CoMPlEx_GUI", "Browse"))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.saveTab), _translate("CoMPlEx_GUI", "Save"))
        self.remoteDock.setWindowTitle(_translate("CoMPlEx_GUI", "Remote"))
        self.channelCmbBox.setItemText(0, _translate("CoMPlEx_GUI", "Engage"))
        self.channelCmbBox.setItemText(1, _translate("CoMPlEx_GUI", "Calibrate QPD"))
        self.channelCmbBox.setItemText(2, _translate("CoMPlEx_GUI", "Calibrate K"))
        self.channelCmbBox.setItemText(3, _translate("CoMPlEx_GUI", "Single Curve"))
        self.channelCmbBox.setItemText(4, _translate("CoMPlEx_GUI", "Single Custom Curve"))
        self.channelCmbBox.setItemText(5, _translate("CoMPlEx_GUI", "Curve Map"))
        self.channelCmbBox.setItemText(6, _translate("CoMPlEx_GUI", "Custom Curve Map"))
        self.playBtn.setText(_translate("CoMPlEx_GUI", "▶"))
        self.stopBtn.setText(_translate("CoMPlEx_GUI", "■"))
        self.action_Set_save_paths.setText(_translate("CoMPlEx_GUI", "&Set save paths"))
        self.action_QPD_and_piezo.setText(_translate("CoMPlEx_GUI", "&QPD and piezo"))
        self.action_Motors.setText(_translate("CoMPlEx_GUI", "&Motors"))
        self.action_General_config.setText(_translate("CoMPlEx_GUI", "&General config"))
        self.action_Controls_config.setText(_translate("CoMPlEx_GUI", "&Controls config"))
        self.action_Settings.setText(_translate("CoMPlEx_GUI", "&Settings"))
        self.action_Remote.setText(_translate("CoMPlEx_GUI", "&Remote"))
        self.action_Save_parameters.setText(_translate("CoMPlEx_GUI", "&Save parameters"))
        self.action_Save_parameters.setShortcut(_translate("CoMPlEx_GUI", "Ctrl+S"))
        self.action_Load_parameters.setText(_translate("CoMPlEx_GUI", "&Load parameters"))
        self.action_Load_parameters.setShortcut(_translate("CoMPlEx_GUI", "Ctrl+L"))
        self.action_Exit.setText(_translate("CoMPlEx_GUI", "&Exit"))
        self.action_Exit.setShortcut(_translate("CoMPlEx_GUI", "Ctrl+Shift+E"))
        self.action_Edit_config.setText(_translate("CoMPlEx_GUI", "E&dit config"))
        self.action_Open_SiMPlE.setText(_translate("CoMPlEx_GUI", "&Open SiMPlE"))

from pyqtgraph import PlotWidget
