# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIs\CoMPlEx_GUI.ui'
#
# Created: Thu Sep 10 18:46:32 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CoMPlEx_GUI(object):
    def setupUi(self, CoMPlEx_GUI):
        CoMPlEx_GUI.setObjectName(_fromUtf8("CoMPlEx_GUI"))
        CoMPlEx_GUI.resize(1115, 896)
        self.centralwidget = QtGui.QWidget(CoMPlEx_GUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.centralPlot = PlotWidget(self.centralwidget)
        self.centralPlot.setObjectName(_fromUtf8("centralPlot"))
        self.gridLayout.addWidget(self.centralPlot, 0, 0, 1, 1)
        CoMPlEx_GUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(CoMPlEx_GUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1115, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Config = QtGui.QMenu(self.menubar)
        self.menu_Config.setObjectName(_fromUtf8("menu_Config"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        self.menu_Analysis = QtGui.QMenu(self.menubar)
        self.menu_Analysis.setObjectName(_fromUtf8("menu_Analysis"))
        CoMPlEx_GUI.setMenuBar(self.menubar)
        self.qpdNpiezoDock = QtGui.QDockWidget(CoMPlEx_GUI)
        self.qpdNpiezoDock.setMaximumSize(QtCore.QSize(524287, 524287))
        self.qpdNpiezoDock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.qpdNpiezoDock.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.qpdNpiezoDock.setObjectName(_fromUtf8("qpdNpiezoDock"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.torsNumDbl = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.torsNumDbl.sizePolicy().hasHeightForWidth())
        self.torsNumDbl.setSizePolicy(sizePolicy)
        self.torsNumDbl.setReadOnly(True)
        self.torsNumDbl.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.torsNumDbl.setDecimals(3)
        self.torsNumDbl.setMinimum(-10.0)
        self.torsNumDbl.setMaximum(10.0)
        self.torsNumDbl.setObjectName(_fromUtf8("torsNumDbl"))
        self.gridLayout_2.addWidget(self.torsNumDbl, 2, 1, 1, 1)
        self.deflNumDbl = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deflNumDbl.sizePolicy().hasHeightForWidth())
        self.deflNumDbl.setSizePolicy(sizePolicy)
        self.deflNumDbl.setReadOnly(True)
        self.deflNumDbl.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.deflNumDbl.setDecimals(3)
        self.deflNumDbl.setMinimum(-10.0)
        self.deflNumDbl.setMaximum(10.0)
        self.deflNumDbl.setObjectName(_fromUtf8("deflNumDbl"))
        self.gridLayout_2.addWidget(self.deflNumDbl, 1, 1, 1, 1)
        self.deflNegProg = QtGui.QProgressBar(self.dockWidgetContents)
        self.deflNegProg.setAutoFillBackground(False)
        self.deflNegProg.setMinimum(0)
        self.deflNegProg.setMaximum(10)
        self.deflNegProg.setProperty("value", 0)
        self.deflNegProg.setTextVisible(False)
        self.deflNegProg.setInvertedAppearance(True)
        self.deflNegProg.setObjectName(_fromUtf8("deflNegProg"))
        self.gridLayout_2.addWidget(self.deflNegProg, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.sumNumDbl = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sumNumDbl.sizePolicy().hasHeightForWidth())
        self.sumNumDbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sumNumDbl.setFont(font)
        self.sumNumDbl.setReadOnly(True)
        self.sumNumDbl.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.sumNumDbl.setDecimals(3)
        self.sumNumDbl.setMinimum(0.0)
        self.sumNumDbl.setMaximum(10.0)
        self.sumNumDbl.setObjectName(_fromUtf8("sumNumDbl"))
        self.gridLayout_2.addWidget(self.sumNumDbl, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.deflPosProg = QtGui.QProgressBar(self.dockWidgetContents)
        self.deflPosProg.setMaximum(10)
        self.deflPosProg.setProperty("value", 0)
        self.deflPosProg.setTextVisible(False)
        self.deflPosProg.setObjectName(_fromUtf8("deflPosProg"))
        self.gridLayout_2.addWidget(self.deflPosProg, 1, 3, 1, 1)
        self.torsNegProg = QtGui.QProgressBar(self.dockWidgetContents)
        self.torsNegProg.setMaximum(10)
        self.torsNegProg.setProperty("value", 0)
        self.torsNegProg.setTextVisible(False)
        self.torsNegProg.setInvertedAppearance(True)
        self.torsNegProg.setObjectName(_fromUtf8("torsNegProg"))
        self.gridLayout_2.addWidget(self.torsNegProg, 2, 2, 1, 1)
        self.torsPosProg = QtGui.QProgressBar(self.dockWidgetContents)
        self.torsPosProg.setMaximum(10)
        self.torsPosProg.setProperty("value", 0)
        self.torsPosProg.setTextVisible(False)
        self.torsPosProg.setObjectName(_fromUtf8("torsPosProg"))
        self.gridLayout_2.addWidget(self.torsPosProg, 2, 3, 1, 1)
        self.sumProg = QtGui.QProgressBar(self.dockWidgetContents)
        self.sumProg.setMaximum(10)
        self.sumProg.setProperty("value", 0)
        self.sumProg.setTextVisible(False)
        self.sumProg.setObjectName(_fromUtf8("sumProg"))
        self.gridLayout_2.addWidget(self.sumProg, 3, 2, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_2.setRowMinimumHeight(0, 2)
        self.gridLayout_2.setRowMinimumHeight(1, 1)
        self.gridLayout_2.setRowMinimumHeight(2, 1)
        self.gridLayout_2.setRowMinimumHeight(3, 1)
        self.gridLayout_2.setRowMinimumHeight(4, 2)
        self.gridLayout_2.setColumnStretch(0, 3)
        self.gridLayout_2.setColumnStretch(1, 3)
        self.gridLayout_2.setColumnStretch(2, 7)
        self.gridLayout_2.setColumnStretch(3, 7)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.dockWidgetContents)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.zPiezoNumDbl = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zPiezoNumDbl.sizePolicy().hasHeightForWidth())
        self.zPiezoNumDbl.setSizePolicy(sizePolicy)
        self.zPiezoNumDbl.setReadOnly(True)
        self.zPiezoNumDbl.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.zPiezoNumDbl.setDecimals(3)
        self.zPiezoNumDbl.setMaximum(10.0)
        self.zPiezoNumDbl.setObjectName(_fromUtf8("zPiezoNumDbl"))
        self.horizontalLayout_2.addWidget(self.zPiezoNumDbl)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.zPiezoProg = QtGui.QProgressBar(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zPiezoProg.sizePolicy().hasHeightForWidth())
        self.zPiezoProg.setSizePolicy(sizePolicy)
        self.zPiezoProg.setMaximum(10)
        self.zPiezoProg.setProperty("value", 0)
        self.zPiezoProg.setAlignment(QtCore.Qt.AlignCenter)
        self.zPiezoProg.setTextVisible(False)
        self.zPiezoProg.setOrientation(QtCore.Qt.Vertical)
        self.zPiezoProg.setObjectName(_fromUtf8("zPiezoProg"))
        self.horizontalLayout_3.addWidget(self.zPiezoProg)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.alignPlot = PlotWidget(self.dockWidgetContents)
        self.alignPlot.setObjectName(_fromUtf8("alignPlot"))
        self.horizontalLayout.addWidget(self.alignPlot)
        self.horizontalLayout.setStretch(0, 8)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 3)
        self.qpdNpiezoDock.setWidget(self.dockWidgetContents)
        CoMPlEx_GUI.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.qpdNpiezoDock)
        self.motorsDock = QtGui.QDockWidget(CoMPlEx_GUI)
        self.motorsDock.setMinimumSize(QtCore.QSize(330, 240))
        self.motorsDock.setMaximumSize(QtCore.QSize(330, 240))
        self.motorsDock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.motorsDock.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.motorsDock.setObjectName(_fromUtf8("motorsDock"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.motorTabs = QtGui.QTabWidget(self.dockWidgetContents_2)
        self.motorTabs.setTabPosition(QtGui.QTabWidget.South)
        self.motorTabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.motorTabs.setDocumentMode(True)
        self.motorTabs.setObjectName(_fromUtf8("motorTabs"))
        self.motManTab = QtGui.QWidget()
        self.motManTab.setObjectName(_fromUtf8("motManTab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.motManTab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.yPlusBtn = QtGui.QPushButton(self.motManTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yPlusBtn.sizePolicy().hasHeightForWidth())
        self.yPlusBtn.setSizePolicy(sizePolicy)
        self.yPlusBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.yPlusBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.yPlusBtn.setObjectName(_fromUtf8("yPlusBtn"))
        self.gridLayout_3.addWidget(self.yPlusBtn, 0, 1, 1, 1)
        self.xMinusBtn = QtGui.QPushButton(self.motManTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xMinusBtn.sizePolicy().hasHeightForWidth())
        self.xMinusBtn.setSizePolicy(sizePolicy)
        self.xMinusBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.xMinusBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.xMinusBtn.setObjectName(_fromUtf8("xMinusBtn"))
        self.gridLayout_3.addWidget(self.xMinusBtn, 1, 0, 1, 1)
        self.xPlusBtn = QtGui.QPushButton(self.motManTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xPlusBtn.sizePolicy().hasHeightForWidth())
        self.xPlusBtn.setSizePolicy(sizePolicy)
        self.xPlusBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.xPlusBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.xPlusBtn.setObjectName(_fromUtf8("xPlusBtn"))
        self.gridLayout_3.addWidget(self.xPlusBtn, 1, 2, 1, 1)
        self.yMinusBtn = QtGui.QPushButton(self.motManTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yMinusBtn.sizePolicy().hasHeightForWidth())
        self.yMinusBtn.setSizePolicy(sizePolicy)
        self.yMinusBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.yMinusBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.yMinusBtn.setObjectName(_fromUtf8("yMinusBtn"))
        self.gridLayout_3.addWidget(self.yMinusBtn, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.motManTab)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.fixCenterBtn = QtGui.QPushButton(self.motManTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixCenterBtn.sizePolicy().hasHeightForWidth())
        self.fixCenterBtn.setSizePolicy(sizePolicy)
        self.fixCenterBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.fixCenterBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.fixCenterBtn.setObjectName(_fromUtf8("fixCenterBtn"))
        self.gridLayout_3.addWidget(self.fixCenterBtn, 1, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_3)
        self.line = QtGui.QFrame(self.motManTab)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_4.addWidget(self.line)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.zPlusBtn = QtGui.QPushButton(self.motManTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zPlusBtn.sizePolicy().hasHeightForWidth())
        self.zPlusBtn.setSizePolicy(sizePolicy)
        self.zPlusBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.zPlusBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.zPlusBtn.setObjectName(_fromUtf8("zPlusBtn"))
        self.verticalLayout_3.addWidget(self.zPlusBtn)
        self.label_6 = QtGui.QLabel(self.motManTab)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.zMinusBtn = QtGui.QPushButton(self.motManTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zMinusBtn.sizePolicy().hasHeightForWidth())
        self.zMinusBtn.setSizePolicy(sizePolicy)
        self.zMinusBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.zMinusBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.zMinusBtn.setAutoDefault(False)
        self.zMinusBtn.setDefault(False)
        self.zMinusBtn.setFlat(False)
        self.zMinusBtn.setObjectName(_fromUtf8("zMinusBtn"))
        self.verticalLayout_3.addWidget(self.zMinusBtn)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.line_2 = QtGui.QFrame(self.motManTab)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_4.addWidget(self.line_2)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.xyStepsLine = QtGui.QLineEdit(self.motManTab)
        self.xyStepsLine.setReadOnly(True)
        self.xyStepsLine.setObjectName(_fromUtf8("xyStepsLine"))
        self.verticalLayout_6.addWidget(self.xyStepsLine)
        self.zStepsLine = QtGui.QLineEdit(self.motManTab)
        self.zStepsLine.setAlignment(QtCore.Qt.AlignCenter)
        self.zStepsLine.setReadOnly(True)
        self.zStepsLine.setObjectName(_fromUtf8("zStepsLine"))
        self.verticalLayout_6.addWidget(self.zStepsLine)
        self.resetXBtn = QtGui.QPushButton(self.motManTab)
        self.resetXBtn.setObjectName(_fromUtf8("resetXBtn"))
        self.verticalLayout_6.addWidget(self.resetXBtn)
        self.resetYBtn = QtGui.QPushButton(self.motManTab)
        self.resetYBtn.setObjectName(_fromUtf8("resetYBtn"))
        self.verticalLayout_6.addWidget(self.resetYBtn)
        self.resetZBtn = QtGui.QPushButton(self.motManTab)
        self.resetZBtn.setObjectName(_fromUtf8("resetZBtn"))
        self.verticalLayout_6.addWidget(self.resetZBtn)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4.setStretch(0, 3)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(4, 2)
        self.motorTabs.addTab(self.motManTab, _fromUtf8(""))
        self.motAutoTab = QtGui.QWidget()
        self.motAutoTab.setObjectName(_fromUtf8("motAutoTab"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.motAutoTab)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.downRightBtn = QtGui.QPushButton(self.motAutoTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downRightBtn.sizePolicy().hasHeightForWidth())
        self.downRightBtn.setSizePolicy(sizePolicy)
        self.downRightBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.downRightBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.downRightBtn.setObjectName(_fromUtf8("downRightBtn"))
        self.gridLayout_9.addWidget(self.downRightBtn, 2, 2, 1, 1)
        self.upRightBtn = QtGui.QPushButton(self.motAutoTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upRightBtn.sizePolicy().hasHeightForWidth())
        self.upRightBtn.setSizePolicy(sizePolicy)
        self.upRightBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.upRightBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.upRightBtn.setObjectName(_fromUtf8("upRightBtn"))
        self.gridLayout_9.addWidget(self.upRightBtn, 0, 2, 1, 1)
        self.upLeftBtn = QtGui.QPushButton(self.motAutoTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upLeftBtn.sizePolicy().hasHeightForWidth())
        self.upLeftBtn.setSizePolicy(sizePolicy)
        self.upLeftBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.upLeftBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.upLeftBtn.setObjectName(_fromUtf8("upLeftBtn"))
        self.gridLayout_9.addWidget(self.upLeftBtn, 0, 0, 1, 1)
        self.downLeftBtn = QtGui.QPushButton(self.motAutoTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.downLeftBtn.sizePolicy().hasHeightForWidth())
        self.downLeftBtn.setSizePolicy(sizePolicy)
        self.downLeftBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.downLeftBtn.setObjectName(_fromUtf8("downLeftBtn"))
        self.gridLayout_9.addWidget(self.downLeftBtn, 2, 0, 1, 1)
        self.centerBtn = QtGui.QPushButton(self.motAutoTab)
        self.centerBtn.setMaximumSize(QtCore.QSize(16777215, 40))
        self.centerBtn.setObjectName(_fromUtf8("centerBtn"))
        self.gridLayout_9.addWidget(self.centerBtn, 1, 1, 1, 1)
        self.stopXyBtn = QtGui.QPushButton(self.motAutoTab)
        self.stopXyBtn.setObjectName(_fromUtf8("stopXyBtn"))
        self.gridLayout_9.addWidget(self.stopXyBtn, 2, 1, 1, 1)
        self.label_42 = QtGui.QLabel(self.motAutoTab)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_9.addWidget(self.label_42, 1, 0, 1, 1)
        self.findCenterBtn = QtGui.QPushButton(self.motAutoTab)
        self.findCenterBtn.setObjectName(_fromUtf8("findCenterBtn"))
        self.gridLayout_9.addWidget(self.findCenterBtn, 0, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.motAutoTab)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_9.addWidget(self.label_43, 1, 2, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_9)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_44 = QtGui.QLabel(self.motAutoTab)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.verticalLayout_8.addWidget(self.label_44)
        self.topBtn = QtGui.QPushButton(self.motAutoTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topBtn.sizePolicy().hasHeightForWidth())
        self.topBtn.setSizePolicy(sizePolicy)
        self.topBtn.setMinimumSize(QtCore.QSize(85, 40))
        self.topBtn.setMaximumSize(QtCore.QSize(85, 40))
        self.topBtn.setObjectName(_fromUtf8("topBtn"))
        self.verticalLayout_8.addWidget(self.topBtn)
        self.stopZBtn = QtGui.QPushButton(self.motAutoTab)
        self.stopZBtn.setObjectName(_fromUtf8("stopZBtn"))
        self.verticalLayout_8.addWidget(self.stopZBtn)
        self.bottomBtn = QtGui.QPushButton(self.motAutoTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottomBtn.sizePolicy().hasHeightForWidth())
        self.bottomBtn.setSizePolicy(sizePolicy)
        self.bottomBtn.setMinimumSize(QtCore.QSize(85, 40))
        self.bottomBtn.setMaximumSize(QtCore.QSize(40, 85))
        self.bottomBtn.setObjectName(_fromUtf8("bottomBtn"))
        self.verticalLayout_8.addWidget(self.bottomBtn)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.horizontalLayout_7.setStretch(0, 4)
        self.horizontalLayout_7.setStretch(1, 1)
        self.motorTabs.addTab(self.motAutoTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.motorTabs)
        self.motorsDock.setWidget(self.dockWidgetContents_2)
        CoMPlEx_GUI.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.motorsDock)
        self.settingsDock = QtGui.QDockWidget(CoMPlEx_GUI)
        self.settingsDock.setMinimumSize(QtCore.QSize(406, 489))
        self.settingsDock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.settingsDock.setAllowedAreas(QtCore.Qt.RightDockWidgetArea)
        self.settingsDock.setObjectName(_fromUtf8("settingsDock"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.functionsTabs = QtGui.QTabWidget(self.dockWidgetContents_3)
        self.functionsTabs.setIconSize(QtCore.QSize(32, 32))
        self.functionsTabs.setTabsClosable(False)
        self.functionsTabs.setObjectName(_fromUtf8("functionsTabs"))
        self.fbTab = QtGui.QWidget()
        self.fbTab.setObjectName(_fromUtf8("fbTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.fbTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.uploadSetPtBtn = QtGui.QPushButton(self.fbTab)
        self.uploadSetPtBtn.setObjectName(_fromUtf8("uploadSetPtBtn"))
        self.gridLayout_4.addWidget(self.uploadSetPtBtn, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.fbTab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.pGainNumDbl = QtGui.QDoubleSpinBox(self.fbTab)
        self.pGainNumDbl.setObjectName(_fromUtf8("pGainNumDbl"))
        self.gridLayout_4.addWidget(self.pGainNumDbl, 2, 1, 1, 1)
        self.setPtNumDbl = QtGui.QDoubleSpinBox(self.fbTab)
        self.setPtNumDbl.setObjectName(_fromUtf8("setPtNumDbl"))
        self.gridLayout_4.addWidget(self.setPtNumDbl, 1, 1, 1, 1)
        self.iGainNumDbl = QtGui.QDoubleSpinBox(self.fbTab)
        self.iGainNumDbl.setObjectName(_fromUtf8("iGainNumDbl"))
        self.gridLayout_4.addWidget(self.iGainNumDbl, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.fbTab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.uploadIGainBtn = QtGui.QPushButton(self.fbTab)
        self.uploadIGainBtn.setObjectName(_fromUtf8("uploadIGainBtn"))
        self.gridLayout_4.addWidget(self.uploadIGainBtn, 3, 2, 1, 1)
        self.uploadPGainBtn = QtGui.QPushButton(self.fbTab)
        self.uploadPGainBtn.setObjectName(_fromUtf8("uploadPGainBtn"))
        self.gridLayout_4.addWidget(self.uploadPGainBtn, 2, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.fbTab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 3, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.fbTab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_4.addWidget(self.line_3, 4, 0, 1, 2)
        self.uploadFbBtn = QtGui.QPushButton(self.fbTab)
        self.uploadFbBtn.setObjectName(_fromUtf8("uploadFbBtn"))
        self.gridLayout_4.addWidget(self.uploadFbBtn, 4, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 5, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 0, 0, 1, 1)
        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(1, 1)
        self.gridLayout_4.setRowStretch(2, 1)
        self.gridLayout_4.setRowStretch(3, 1)
        self.gridLayout_4.setRowStretch(4, 1)
        self.gridLayout_4.setRowStretch(5, 20)
        self.functionsTabs.addTab(self.fbTab, _fromUtf8(""))
        self.calibQpdTab = QtGui.QWidget()
        self.calibQpdTab.setObjectName(_fromUtf8("calibQpdTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.calibQpdTab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.uploadCalibStimFreqBtn = QtGui.QPushButton(self.calibQpdTab)
        self.uploadCalibStimFreqBtn.setObjectName(_fromUtf8("uploadCalibStimFreqBtn"))
        self.gridLayout_5.addWidget(self.uploadCalibStimFreqBtn, 5, 2, 1, 1)
        self.calibStimFreqNumDbl = QtGui.QDoubleSpinBox(self.calibQpdTab)
        self.calibStimFreqNumDbl.setObjectName(_fromUtf8("calibStimFreqNumDbl"))
        self.gridLayout_5.addWidget(self.calibStimFreqNumDbl, 5, 1, 1, 1)
        self.calibStimZOffsetNumDbl = QtGui.QDoubleSpinBox(self.calibQpdTab)
        self.calibStimZOffsetNumDbl.setObjectName(_fromUtf8("calibStimZOffsetNumDbl"))
        self.gridLayout_5.addWidget(self.calibStimZOffsetNumDbl, 3, 1, 1, 1)
        self.line_4 = QtGui.QFrame(self.calibQpdTab)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_5.addWidget(self.line_4, 2, 0, 1, 3)
        self.kdNumDbl = QtGui.QDoubleSpinBox(self.calibQpdTab)
        self.kdNumDbl.setObjectName(_fromUtf8("kdNumDbl"))
        self.gridLayout_5.addWidget(self.kdNumDbl, 1, 1, 1, 1)
        self.uploadKdBtn = QtGui.QPushButton(self.calibQpdTab)
        self.uploadKdBtn.setObjectName(_fromUtf8("uploadKdBtn"))
        self.gridLayout_5.addWidget(self.uploadKdBtn, 1, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.calibQpdTab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_5.addWidget(self.label_13, 5, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.calibQpdTab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.calibQpdTab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 3, 0, 1, 1)
        self.uploadCalibStimZOffsetBtn = QtGui.QPushButton(self.calibQpdTab)
        self.uploadCalibStimZOffsetBtn.setObjectName(_fromUtf8("uploadCalibStimZOffsetBtn"))
        self.gridLayout_5.addWidget(self.uploadCalibStimZOffsetBtn, 3, 2, 1, 1)
        self.uploadCalibStimAmplBtn = QtGui.QPushButton(self.calibQpdTab)
        self.uploadCalibStimAmplBtn.setObjectName(_fromUtf8("uploadCalibStimAmplBtn"))
        self.gridLayout_5.addWidget(self.uploadCalibStimAmplBtn, 4, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.calibQpdTab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 1)
        self.calibStimAmplNumDbl = QtGui.QDoubleSpinBox(self.calibQpdTab)
        self.calibStimAmplNumDbl.setObjectName(_fromUtf8("calibStimAmplNumDbl"))
        self.gridLayout_5.addWidget(self.calibStimAmplNumDbl, 4, 1, 1, 1)
        self.line_5 = QtGui.QFrame(self.calibQpdTab)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_5.addWidget(self.line_5, 6, 0, 1, 2)
        self.uploadCalibStimBtn = QtGui.QPushButton(self.calibQpdTab)
        self.uploadCalibStimBtn.setObjectName(_fromUtf8("uploadCalibStimBtn"))
        self.gridLayout_5.addWidget(self.uploadCalibStimBtn, 6, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 7, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem5, 0, 0, 1, 1)
        self.gridLayout_5.setRowStretch(0, 1)
        self.gridLayout_5.setRowStretch(1, 1)
        self.gridLayout_5.setRowStretch(2, 1)
        self.gridLayout_5.setRowStretch(3, 1)
        self.gridLayout_5.setRowStretch(4, 1)
        self.gridLayout_5.setRowStretch(5, 1)
        self.gridLayout_5.setRowStretch(6, 1)
        self.gridLayout_5.setRowStretch(7, 20)
        self.functionsTabs.addTab(self.calibQpdTab, _fromUtf8(""))
        self.calibKTab = QtGui.QWidget()
        self.calibKTab.setObjectName(_fromUtf8("calibKTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.calibKTab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_17 = QtGui.QLabel(self.calibKTab)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_6.addWidget(self.label_17, 4, 0, 1, 1)
        self.uploadClWidBtn = QtGui.QPushButton(self.calibKTab)
        self.uploadClWidBtn.setObjectName(_fromUtf8("uploadClWidBtn"))
        self.gridLayout_6.addWidget(self.uploadClWidBtn, 5, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.calibKTab)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_6.addWidget(self.label_16, 3, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.calibKTab)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_6.addWidget(self.label_18, 5, 0, 1, 1)
        self.uploadPkStartFreqBtn = QtGui.QPushButton(self.calibKTab)
        self.uploadPkStartFreqBtn.setObjectName(_fromUtf8("uploadPkStartFreqBtn"))
        self.gridLayout_6.addWidget(self.uploadPkStartFreqBtn, 2, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.calibKTab)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_6.addWidget(self.label_20, 7, 0, 1, 1)
        self.clLenNumDbl = QtGui.QDoubleSpinBox(self.calibKTab)
        self.clLenNumDbl.setObjectName(_fromUtf8("clLenNumDbl"))
        self.gridLayout_6.addWidget(self.clLenNumDbl, 4, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.calibKTab)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_6.addWidget(self.label_14, 0, 0, 1, 1)
        self.uploadClLenBtn = QtGui.QPushButton(self.calibKTab)
        self.uploadClLenBtn.setObjectName(_fromUtf8("uploadClLenBtn"))
        self.gridLayout_6.addWidget(self.uploadClLenBtn, 4, 2, 1, 1)
        self.uploadKBtn = QtGui.QPushButton(self.calibKTab)
        self.uploadKBtn.setObjectName(_fromUtf8("uploadKBtn"))
        self.gridLayout_6.addWidget(self.uploadKBtn, 0, 2, 1, 1)
        self.uploadMediumDensBtn = QtGui.QPushButton(self.calibKTab)
        self.uploadMediumDensBtn.setObjectName(_fromUtf8("uploadMediumDensBtn"))
        self.gridLayout_6.addWidget(self.uploadMediumDensBtn, 6, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.calibKTab)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_6.addWidget(self.label_15, 2, 0, 1, 1)
        self.mediumViscNumDbl = QtGui.QDoubleSpinBox(self.calibKTab)
        self.mediumViscNumDbl.setObjectName(_fromUtf8("mediumViscNumDbl"))
        self.gridLayout_6.addWidget(self.mediumViscNumDbl, 7, 1, 1, 1)
        self.uploadMediumViscBtn = QtGui.QPushButton(self.calibKTab)
        self.uploadMediumViscBtn.setObjectName(_fromUtf8("uploadMediumViscBtn"))
        self.gridLayout_6.addWidget(self.uploadMediumViscBtn, 7, 2, 1, 1)
        self.line_6 = QtGui.QFrame(self.calibKTab)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_6.addWidget(self.line_6, 1, 0, 1, 3)
        self.pkEndFreqNumDbl = QtGui.QDoubleSpinBox(self.calibKTab)
        self.pkEndFreqNumDbl.setObjectName(_fromUtf8("pkEndFreqNumDbl"))
        self.gridLayout_6.addWidget(self.pkEndFreqNumDbl, 3, 1, 1, 1)
        self.uploadPkEndFreqBtn = QtGui.QPushButton(self.calibKTab)
        self.uploadPkEndFreqBtn.setObjectName(_fromUtf8("uploadPkEndFreqBtn"))
        self.gridLayout_6.addWidget(self.uploadPkEndFreqBtn, 3, 2, 1, 1)
        self.mediumDensNumDbl = QtGui.QDoubleSpinBox(self.calibKTab)
        self.mediumDensNumDbl.setObjectName(_fromUtf8("mediumDensNumDbl"))
        self.gridLayout_6.addWidget(self.mediumDensNumDbl, 6, 1, 1, 1)
        self.pkStartFreqNumDbl = QtGui.QDoubleSpinBox(self.calibKTab)
        self.pkStartFreqNumDbl.setObjectName(_fromUtf8("pkStartFreqNumDbl"))
        self.gridLayout_6.addWidget(self.pkStartFreqNumDbl, 2, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.calibKTab)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_6.addWidget(self.label_19, 6, 0, 1, 1)
        self.clWidNumDbl = QtGui.QDoubleSpinBox(self.calibKTab)
        self.clWidNumDbl.setObjectName(_fromUtf8("clWidNumDbl"))
        self.gridLayout_6.addWidget(self.clWidNumDbl, 5, 1, 1, 1)
        self.kNumDbl = QtGui.QDoubleSpinBox(self.calibKTab)
        self.kNumDbl.setObjectName(_fromUtf8("kNumDbl"))
        self.gridLayout_6.addWidget(self.kNumDbl, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.calibKTab)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_6.addWidget(self.label_21, 9, 0, 1, 1)
        self.avgNumNum = QtGui.QSpinBox(self.calibKTab)
        self.avgNumNum.setObjectName(_fromUtf8("avgNumNum"))
        self.gridLayout_6.addWidget(self.avgNumNum, 9, 1, 1, 1)
        self.line_7 = QtGui.QFrame(self.calibKTab)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_6.addWidget(self.line_7, 8, 0, 1, 2)
        self.uploadKCalibBtn = QtGui.QPushButton(self.calibKTab)
        self.uploadKCalibBtn.setObjectName(_fromUtf8("uploadKCalibBtn"))
        self.gridLayout_6.addWidget(self.uploadKCalibBtn, 8, 2, 1, 1)
        self.functionsTabs.addTab(self.calibKTab, _fromUtf8(""))
        self.fvsdTab = QtGui.QWidget()
        self.fvsdTab.setObjectName(_fromUtf8("fvsdTab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.fvsdTab)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_26 = QtGui.QLabel(self.fvsdTab)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_7.addWidget(self.label_26, 4, 0, 1, 1)
        self.endZNumDbl = QtGui.QDoubleSpinBox(self.fvsdTab)
        self.endZNumDbl.setObjectName(_fromUtf8("endZNumDbl"))
        self.gridLayout_7.addWidget(self.endZNumDbl, 2, 1, 1, 1)
        self.holdTimeNumDbl = QtGui.QDoubleSpinBox(self.fvsdTab)
        self.holdTimeNumDbl.setObjectName(_fromUtf8("holdTimeNumDbl"))
        self.gridLayout_7.addWidget(self.holdTimeNumDbl, 5, 1, 1, 1)
        self.uploadFvsdBtn = QtGui.QPushButton(self.fvsdTab)
        self.uploadFvsdBtn.setObjectName(_fromUtf8("uploadFvsdBtn"))
        self.gridLayout_7.addWidget(self.uploadFvsdBtn, 6, 2, 1, 1)
        self.uploadStartZBtn = QtGui.QPushButton(self.fvsdTab)
        self.uploadStartZBtn.setObjectName(_fromUtf8("uploadStartZBtn"))
        self.gridLayout_7.addWidget(self.uploadStartZBtn, 1, 2, 1, 1)
        self.uploadRetrSpeedBtn = QtGui.QPushButton(self.fvsdTab)
        self.uploadRetrSpeedBtn.setObjectName(_fromUtf8("uploadRetrSpeedBtn"))
        self.gridLayout_7.addWidget(self.uploadRetrSpeedBtn, 4, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.fvsdTab)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_7.addWidget(self.label_24, 2, 0, 1, 1)
        self.maxFNumDbl = QtGui.QDoubleSpinBox(self.fvsdTab)
        self.maxFNumDbl.setObjectName(_fromUtf8("maxFNumDbl"))
        self.gridLayout_7.addWidget(self.maxFNumDbl, 0, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.fvsdTab)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_7.addWidget(self.label_23, 1, 0, 1, 1)
        self.uploadAppSpeedBtn = QtGui.QPushButton(self.fvsdTab)
        self.uploadAppSpeedBtn.setObjectName(_fromUtf8("uploadAppSpeedBtn"))
        self.gridLayout_7.addWidget(self.uploadAppSpeedBtn, 3, 2, 1, 1)
        self.label_22 = QtGui.QLabel(self.fvsdTab)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_7.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.fvsdTab)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_7.addWidget(self.label_27, 5, 0, 1, 1)
        self.uploadHoldTimeBtn = QtGui.QPushButton(self.fvsdTab)
        self.uploadHoldTimeBtn.setObjectName(_fromUtf8("uploadHoldTimeBtn"))
        self.gridLayout_7.addWidget(self.uploadHoldTimeBtn, 5, 2, 1, 1)
        self.curveNumNum = QtGui.QDoubleSpinBox(self.fvsdTab)
        self.curveNumNum.setObjectName(_fromUtf8("curveNumNum"))
        self.gridLayout_7.addWidget(self.curveNumNum, 8, 1, 1, 1)
        self.constForceCkBox = QtGui.QCheckBox(self.fvsdTab)
        self.constForceCkBox.setObjectName(_fromUtf8("constForceCkBox"))
        self.gridLayout_7.addWidget(self.constForceCkBox, 7, 0, 1, 1)
        self.startZNumDbl = QtGui.QDoubleSpinBox(self.fvsdTab)
        self.startZNumDbl.setObjectName(_fromUtf8("startZNumDbl"))
        self.gridLayout_7.addWidget(self.startZNumDbl, 1, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.fvsdTab)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_7.addWidget(self.label_25, 3, 0, 1, 1)
        self.uploadEndZBtn = QtGui.QPushButton(self.fvsdTab)
        self.uploadEndZBtn.setObjectName(_fromUtf8("uploadEndZBtn"))
        self.gridLayout_7.addWidget(self.uploadEndZBtn, 2, 2, 1, 1)
        self.appSpeedNumDbl = QtGui.QDoubleSpinBox(self.fvsdTab)
        self.appSpeedNumDbl.setObjectName(_fromUtf8("appSpeedNumDbl"))
        self.gridLayout_7.addWidget(self.appSpeedNumDbl, 3, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.fvsdTab)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_7.addWidget(self.label_28, 8, 0, 1, 1)
        self.uploadMaxFBtn = QtGui.QPushButton(self.fvsdTab)
        self.uploadMaxFBtn.setObjectName(_fromUtf8("uploadMaxFBtn"))
        self.gridLayout_7.addWidget(self.uploadMaxFBtn, 0, 2, 1, 1)
        self.restrSpeedNumDbl = QtGui.QDoubleSpinBox(self.fvsdTab)
        self.restrSpeedNumDbl.setObjectName(_fromUtf8("restrSpeedNumDbl"))
        self.gridLayout_7.addWidget(self.restrSpeedNumDbl, 4, 1, 1, 1)
        self.line_8 = QtGui.QFrame(self.fvsdTab)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_7.addWidget(self.line_8, 6, 0, 1, 2)
        self.functionsTabs.addTab(self.fvsdTab, _fromUtf8(""))
        self.custFvsdTab = QtGui.QWidget()
        self.custFvsdTab.setEnabled(True)
        self.custFvsdTab.setObjectName(_fromUtf8("custFvsdTab"))
        self.gridLayout_8 = QtGui.QGridLayout(self.custFvsdTab)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.segCmbBox = QtGui.QComboBox(self.custFvsdTab)
        self.segCmbBox.setObjectName(_fromUtf8("segCmbBox"))
        self.gridLayout_8.addWidget(self.segCmbBox, 8, 0, 1, 2)
        self.removeSegBtn = QtGui.QPushButton(self.custFvsdTab)
        self.removeSegBtn.setObjectName(_fromUtf8("removeSegBtn"))
        self.gridLayout_8.addWidget(self.removeSegBtn, 8, 3, 1, 1)
        self.label_31 = QtGui.QLabel(self.custFvsdTab)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_8.addWidget(self.label_31, 4, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.custFvsdTab)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_8.addWidget(self.label_30, 3, 0, 1, 1)
        self.holdTimecNumDbl = QtGui.QDoubleSpinBox(self.custFvsdTab)
        self.holdTimecNumDbl.setEnabled(False)
        self.holdTimecNumDbl.setObjectName(_fromUtf8("holdTimecNumDbl"))
        self.gridLayout_8.addWidget(self.holdTimecNumDbl, 6, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.custFvsdTab)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_8.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_45 = QtGui.QLabel(self.custFvsdTab)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_8.addWidget(self.label_45, 10, 0, 1, 1)
        self.label_35 = QtGui.QLabel(self.custFvsdTab)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_8.addWidget(self.label_35, 6, 0, 1, 1)
        self.uploadStartZcBtn = QtGui.QPushButton(self.custFvsdTab)
        self.uploadStartZcBtn.setObjectName(_fromUtf8("uploadStartZcBtn"))
        self.gridLayout_8.addWidget(self.uploadStartZcBtn, 0, 3, 1, 1)
        self.endFcNumDbl = QtGui.QDoubleSpinBox(self.custFvsdTab)
        self.endFcNumDbl.setObjectName(_fromUtf8("endFcNumDbl"))
        self.gridLayout_8.addWidget(self.endFcNumDbl, 4, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.custFvsdTab)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_8.addWidget(self.label_46, 5, 0, 1, 1)
        self.curveNumcNum = QtGui.QSpinBox(self.custFvsdTab)
        self.curveNumcNum.setObjectName(_fromUtf8("curveNumcNum"))
        self.gridLayout_8.addWidget(self.curveNumcNum, 10, 1, 1, 1)
        self.showZTravelBtn = QtGui.QPushButton(self.custFvsdTab)
        self.showZTravelBtn.setObjectName(_fromUtf8("showZTravelBtn"))
        self.gridLayout_8.addWidget(self.showZTravelBtn, 9, 0, 1, 4)
        self.updateSegBtn = QtGui.QPushButton(self.custFvsdTab)
        self.updateSegBtn.setObjectName(_fromUtf8("updateSegBtn"))
        self.gridLayout_8.addWidget(self.updateSegBtn, 8, 2, 1, 1)
        self.endZcNumDbl = QtGui.QDoubleSpinBox(self.custFvsdTab)
        self.endZcNumDbl.setObjectName(_fromUtf8("endZcNumDbl"))
        self.gridLayout_8.addWidget(self.endZcNumDbl, 3, 1, 1, 1)
        self.line_9 = QtGui.QFrame(self.custFvsdTab)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout_8.addWidget(self.line_9, 1, 0, 1, 4)
        self.speedcNumDbl = QtGui.QDoubleSpinBox(self.custFvsdTab)
        self.speedcNumDbl.setEnabled(True)
        self.speedcNumDbl.setObjectName(_fromUtf8("speedcNumDbl"))
        self.gridLayout_8.addWidget(self.speedcNumDbl, 5, 1, 1, 1)
        self.startZcNumDbl = QtGui.QDoubleSpinBox(self.custFvsdTab)
        self.startZcNumDbl.setObjectName(_fromUtf8("startZcNumDbl"))
        self.gridLayout_8.addWidget(self.startZcNumDbl, 0, 1, 1, 1)
        self.altZSegBtn = QtGui.QPushButton(self.custFvsdTab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/altZ.bmp")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.altZSegBtn.setIcon(icon)
        self.altZSegBtn.setIconSize(QtCore.QSize(20, 20))
        self.altZSegBtn.setCheckable(False)
        self.altZSegBtn.setDefault(False)
        self.altZSegBtn.setObjectName(_fromUtf8("altZSegBtn"))
        self.gridLayout_8.addWidget(self.altZSegBtn, 2, 0, 1, 1)
        self.altFSegBtn = QtGui.QPushButton(self.custFvsdTab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/altF.bmp")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.altFSegBtn.setIcon(icon1)
        self.altFSegBtn.setIconSize(QtCore.QSize(20, 20))
        self.altFSegBtn.setCheckable(False)
        self.altFSegBtn.setObjectName(_fromUtf8("altFSegBtn"))
        self.gridLayout_8.addWidget(self.altFSegBtn, 2, 1, 1, 1)
        self.farSegBtn = QtGui.QPushButton(self.custFvsdTab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/far.bmp")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.farSegBtn.setIcon(icon2)
        self.farSegBtn.setIconSize(QtCore.QSize(20, 20))
        self.farSegBtn.setCheckable(False)
        self.farSegBtn.setObjectName(_fromUtf8("farSegBtn"))
        self.gridLayout_8.addWidget(self.farSegBtn, 2, 2, 1, 1)
        self.nearSegBtn = QtGui.QPushButton(self.custFvsdTab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/near.bmp")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nearSegBtn.setIcon(icon3)
        self.nearSegBtn.setIconSize(QtCore.QSize(20, 20))
        self.nearSegBtn.setCheckable(False)
        self.nearSegBtn.setChecked(False)
        self.nearSegBtn.setObjectName(_fromUtf8("nearSegBtn"))
        self.gridLayout_8.addWidget(self.nearSegBtn, 2, 3, 1, 1)
        self.addSegBtn = QtGui.QPushButton(self.custFvsdTab)
        self.addSegBtn.setObjectName(_fromUtf8("addSegBtn"))
        self.gridLayout_8.addWidget(self.addSegBtn, 7, 0, 1, 2)
        self.functionsTabs.addTab(self.custFvsdTab, _fromUtf8(""))
        self.motorTab = QtGui.QWidget()
        self.motorTab.setObjectName(_fromUtf8("motorTab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.motorTab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_2 = QtGui.QGroupBox(self.motorTab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_39 = QtGui.QLabel(self.groupBox_2)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_39)
        self.xStepNumNum = QtGui.QSpinBox(self.groupBox_2)
        self.xStepNumNum.setObjectName(_fromUtf8("xStepNumNum"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.xStepNumNum)
        self.label_40 = QtGui.QLabel(self.groupBox_2)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_40)
        self.yStepNumNum = QtGui.QSpinBox(self.groupBox_2)
        self.yStepNumNum.setObjectName(_fromUtf8("yStepNumNum"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.yStepNumNum)
        self.label_41 = QtGui.QLabel(self.groupBox_2)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_41)
        self.zStepNumNum = QtGui.QSpinBox(self.groupBox_2)
        self.zStepNumNum.setObjectName(_fromUtf8("zStepNumNum"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.zStepNumNum)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.motorTab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_36 = QtGui.QLabel(self.groupBox)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_36)
        self.xStepNumMapNum = QtGui.QSpinBox(self.groupBox)
        self.xStepNumMapNum.setObjectName(_fromUtf8("xStepNumMapNum"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.xStepNumMapNum)
        self.label_37 = QtGui.QLabel(self.groupBox)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_37)
        self.yStepNumMapNum = QtGui.QSpinBox(self.groupBox)
        self.yStepNumMapNum.setObjectName(_fromUtf8("yStepNumMapNum"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.yStepNumMapNum)
        self.label_38 = QtGui.QLabel(self.groupBox)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_38)
        self.ptNumMapNum = QtGui.QSpinBox(self.groupBox)
        self.ptNumMapNum.setObjectName(_fromUtf8("ptNumMapNum"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.ptNumMapNum)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.functionsTabs.addTab(self.motorTab, _fromUtf8(""))
        self.saveTab = QtGui.QWidget()
        self.saveTab.setObjectName(_fromUtf8("saveTab"))
        self.gridLayout_10 = QtGui.QGridLayout(self.saveTab)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.fileNameRootLine = QtGui.QLineEdit(self.saveTab)
        self.fileNameRootLine.setObjectName(_fromUtf8("fileNameRootLine"))
        self.gridLayout_10.addWidget(self.fileNameRootLine, 1, 1, 1, 1)
        self.label_48 = QtGui.QLabel(self.saveTab)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_10.addWidget(self.label_48, 2, 0, 1, 1)
        self.label_47 = QtGui.QLabel(self.saveTab)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_10.addWidget(self.label_47, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem6, 3, 0, 1, 1)
        self.dirLine = QtGui.QLineEdit(self.saveTab)
        self.dirLine.setObjectName(_fromUtf8("dirLine"))
        self.gridLayout_10.addWidget(self.dirLine, 2, 1, 1, 1)
        self.browseBtn = QtGui.QPushButton(self.saveTab)
        self.browseBtn.setObjectName(_fromUtf8("browseBtn"))
        self.gridLayout_10.addWidget(self.browseBtn, 2, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem7, 0, 1, 1, 1)
        self.gridLayout_10.setRowStretch(0, 1)
        self.gridLayout_10.setRowStretch(1, 1)
        self.gridLayout_10.setRowStretch(2, 1)
        self.gridLayout_10.setRowStretch(3, 20)
        self.functionsTabs.addTab(self.saveTab, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.functionsTabs)
        self.settingsDock.setWidget(self.dockWidgetContents_3)
        CoMPlEx_GUI.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.settingsDock)
        self.remoteDock = QtGui.QDockWidget(CoMPlEx_GUI)
        self.remoteDock.setMinimumSize(QtCore.QSize(251, 130))
        self.remoteDock.setMaximumSize(QtCore.QSize(524287, 130))
        self.remoteDock.setObjectName(_fromUtf8("remoteDock"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.channelCmbBox = QtGui.QComboBox(self.dockWidgetContents_4)
        self.channelCmbBox.setObjectName(_fromUtf8("channelCmbBox"))
        self.channelCmbBox.addItem(_fromUtf8(""))
        self.channelCmbBox.addItem(_fromUtf8(""))
        self.channelCmbBox.addItem(_fromUtf8(""))
        self.channelCmbBox.addItem(_fromUtf8(""))
        self.channelCmbBox.addItem(_fromUtf8(""))
        self.channelCmbBox.addItem(_fromUtf8(""))
        self.channelCmbBox.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.channelCmbBox)
        self.rdsLine = QtGui.QLineEdit(self.dockWidgetContents_4)
        self.rdsLine.setReadOnly(True)
        self.rdsLine.setObjectName(_fromUtf8("rdsLine"))
        self.horizontalLayout_6.addWidget(self.rdsLine)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.playBtn = QtGui.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playBtn.sizePolicy().hasHeightForWidth())
        self.playBtn.setSizePolicy(sizePolicy)
        self.playBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.playBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.playBtn.setObjectName(_fromUtf8("playBtn"))
        self.horizontalLayout_5.addWidget(self.playBtn)
        self.stopBtn = QtGui.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopBtn.sizePolicy().hasHeightForWidth())
        self.stopBtn.setSizePolicy(sizePolicy)
        self.stopBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.stopBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.stopBtn.setObjectName(_fromUtf8("stopBtn"))
        self.horizontalLayout_5.addWidget(self.stopBtn)
        self.remoteProg = QtGui.QProgressBar(self.dockWidgetContents_4)
        self.remoteProg.setProperty("value", 0)
        self.remoteProg.setObjectName(_fromUtf8("remoteProg"))
        self.horizontalLayout_5.addWidget(self.remoteProg)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.remoteDock.setWidget(self.dockWidgetContents_4)
        CoMPlEx_GUI.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.remoteDock)
        self.action_Set_save_paths = QtGui.QAction(CoMPlEx_GUI)
        self.action_Set_save_paths.setObjectName(_fromUtf8("action_Set_save_paths"))
        self.action_QPD_and_piezo = QtGui.QAction(CoMPlEx_GUI)
        self.action_QPD_and_piezo.setCheckable(True)
        self.action_QPD_and_piezo.setChecked(True)
        self.action_QPD_and_piezo.setObjectName(_fromUtf8("action_QPD_and_piezo"))
        self.action_Motors = QtGui.QAction(CoMPlEx_GUI)
        self.action_Motors.setCheckable(True)
        self.action_Motors.setChecked(True)
        self.action_Motors.setObjectName(_fromUtf8("action_Motors"))
        self.action_General_config = QtGui.QAction(CoMPlEx_GUI)
        self.action_General_config.setObjectName(_fromUtf8("action_General_config"))
        self.action_Controls_config = QtGui.QAction(CoMPlEx_GUI)
        self.action_Controls_config.setObjectName(_fromUtf8("action_Controls_config"))
        self.action_Settings = QtGui.QAction(CoMPlEx_GUI)
        self.action_Settings.setCheckable(True)
        self.action_Settings.setChecked(True)
        self.action_Settings.setObjectName(_fromUtf8("action_Settings"))
        self.action_Remote = QtGui.QAction(CoMPlEx_GUI)
        self.action_Remote.setCheckable(True)
        self.action_Remote.setChecked(True)
        self.action_Remote.setObjectName(_fromUtf8("action_Remote"))
        self.action_Save_parameters = QtGui.QAction(CoMPlEx_GUI)
        self.action_Save_parameters.setObjectName(_fromUtf8("action_Save_parameters"))
        self.action_Load_parameters = QtGui.QAction(CoMPlEx_GUI)
        self.action_Load_parameters.setObjectName(_fromUtf8("action_Load_parameters"))
        self.action_Exit = QtGui.QAction(CoMPlEx_GUI)
        self.action_Exit.setObjectName(_fromUtf8("action_Exit"))
        self.action_Edit_config = QtGui.QAction(CoMPlEx_GUI)
        self.action_Edit_config.setObjectName(_fromUtf8("action_Edit_config"))
        self.action_Open_SiMPlE = QtGui.QAction(CoMPlEx_GUI)
        self.action_Open_SiMPlE.setObjectName(_fromUtf8("action_Open_SiMPlE"))
        self.menu_Config.addAction(self.action_Save_parameters)
        self.menu_Config.addAction(self.action_Load_parameters)
        self.menu_Config.addAction(self.action_Edit_config)
        self.menu_Config.addAction(self.action_Exit)
        self.menu_View.addAction(self.action_QPD_and_piezo)
        self.menu_View.addAction(self.action_Motors)
        self.menu_View.addAction(self.action_Settings)
        self.menu_View.addAction(self.action_Remote)
        self.menu_Analysis.addAction(self.action_Open_SiMPlE)
        self.menubar.addAction(self.menu_Config.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Analysis.menuAction())

        self.retranslateUi(CoMPlEx_GUI)
        self.motorTabs.setCurrentIndex(0)
        self.functionsTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CoMPlEx_GUI)

    def retranslateUi(self, CoMPlEx_GUI):
        CoMPlEx_GUI.setWindowTitle(_translate("CoMPlEx_GUI", "MainWindow", None))
        self.menu_Config.setTitle(_translate("CoMPlEx_GUI", "&File", None))
        self.menu_View.setTitle(_translate("CoMPlEx_GUI", "&View", None))
        self.menu_Analysis.setTitle(_translate("CoMPlEx_GUI", "&Analysis", None))
        self.qpdNpiezoDock.setWindowTitle(_translate("CoMPlEx_GUI", "QPD and piezo monitor", None))
        self.label_3.setText(_translate("CoMPlEx_GUI", "Sum [V]", None))
        self.label.setText(_translate("CoMPlEx_GUI", "Deflection [V]", None))
        self.label_2.setText(_translate("CoMPlEx_GUI", "Torsion [V]", None))
        self.label_4.setText(_translate("CoMPlEx_GUI", "Z [um]", None))
        self.motorsDock.setWindowTitle(_translate("CoMPlEx_GUI", "Motors", None))
        self.yPlusBtn.setText(_translate("CoMPlEx_GUI", "△", None))
        self.xMinusBtn.setText(_translate("CoMPlEx_GUI", "◁", None))
        self.xPlusBtn.setText(_translate("CoMPlEx_GUI", "▷", None))
        self.yMinusBtn.setText(_translate("CoMPlEx_GUI", "▽", None))
        self.label_5.setText(_translate("CoMPlEx_GUI", "XY", None))
        self.fixCenterBtn.setText(_translate("CoMPlEx_GUI", "0", None))
        self.zPlusBtn.setText(_translate("CoMPlEx_GUI", "△", None))
        self.label_6.setText(_translate("CoMPlEx_GUI", "z", None))
        self.zMinusBtn.setText(_translate("CoMPlEx_GUI", "▽", None))
        self.resetXBtn.setText(_translate("CoMPlEx_GUI", "Reset X", None))
        self.resetYBtn.setText(_translate("CoMPlEx_GUI", "Reset Y", None))
        self.resetZBtn.setText(_translate("CoMPlEx_GUI", "Reset Z", None))
        self.motorTabs.setTabText(self.motorTabs.indexOf(self.motManTab), _translate("CoMPlEx_GUI", "Manual", None))
        self.downRightBtn.setText(_translate("CoMPlEx_GUI", "◿", None))
        self.upRightBtn.setText(_translate("CoMPlEx_GUI", "◹", None))
        self.upLeftBtn.setText(_translate("CoMPlEx_GUI", "◸", None))
        self.downLeftBtn.setText(_translate("CoMPlEx_GUI", "◺", None))
        self.centerBtn.setText(_translate("CoMPlEx_GUI", "⊕", None))
        self.stopXyBtn.setText(_translate("CoMPlEx_GUI", "STOP", None))
        self.label_42.setText(_translate("CoMPlEx_GUI", "XY", None))
        self.findCenterBtn.setText(_translate("CoMPlEx_GUI", "Find center", None))
        self.label_43.setText(_translate("CoMPlEx_GUI", "XY", None))
        self.label_44.setText(_translate("CoMPlEx_GUI", "Z", None))
        self.topBtn.setText(_translate("CoMPlEx_GUI", "⊤", None))
        self.stopZBtn.setText(_translate("CoMPlEx_GUI", "STOP", None))
        self.bottomBtn.setText(_translate("CoMPlEx_GUI", "⊥", None))
        self.motorTabs.setTabText(self.motorTabs.indexOf(self.motAutoTab), _translate("CoMPlEx_GUI", "Auto", None))
        self.settingsDock.setWindowTitle(_translate("CoMPlEx_GUI", "Settings", None))
        self.uploadSetPtBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_7.setText(_translate("CoMPlEx_GUI", "Set Point [V]", None))
        self.label_8.setText(_translate("CoMPlEx_GUI", "P Gain", None))
        self.uploadIGainBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.uploadPGainBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_9.setText(_translate("CoMPlEx_GUI", "I Gain", None))
        self.uploadFbBtn.setText(_translate("CoMPlEx_GUI", "Upload All", None))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.fbTab), _translate("CoMPlEx_GUI", "Feedback", None))
        self.uploadCalibStimFreqBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.uploadKdBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_13.setText(_translate("CoMPlEx_GUI", "Frequency [Hz]", None))
        self.label_12.setText(_translate("CoMPlEx_GUI", "Amplitude [nm]", None))
        self.label_11.setText(_translate("CoMPlEx_GUI", "Z offset [nm]", None))
        self.uploadCalibStimZOffsetBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.uploadCalibStimAmplBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_10.setText(_translate("CoMPlEx_GUI", "Kd [nm/V]", None))
        self.uploadCalibStimBtn.setText(_translate("CoMPlEx_GUI", "Upload All", None))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.calibQpdTab), _translate("CoMPlEx_GUI", "QPD Calibration", None))
        self.label_17.setText(_translate("CoMPlEx_GUI", "Cant. Length [nm]", None))
        self.uploadClWidBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_16.setText(_translate("CoMPlEx_GUI", "Peak end freq[Hz]", None))
        self.label_18.setText(_translate("CoMPlEx_GUI", "Cant. Width [nm]", None))
        self.uploadPkStartFreqBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_20.setText(_translate("CoMPlEx_GUI", "Medium visc. [nm]", None))
        self.label_14.setText(_translate("CoMPlEx_GUI", "K [pN/nm]", None))
        self.uploadClLenBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.uploadKBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.uploadMediumDensBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_15.setText(_translate("CoMPlEx_GUI", "Peak start freq[Hz]", None))
        self.uploadMediumViscBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.uploadPkEndFreqBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_19.setText(_translate("CoMPlEx_GUI", "Medium dens. [nm]", None))
        self.label_21.setText(_translate("CoMPlEx_GUI", "Average Num", None))
        self.uploadKCalibBtn.setText(_translate("CoMPlEx_GUI", "Upload All", None))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.calibKTab), _translate("CoMPlEx_GUI", "K Calibration", None))
        self.label_26.setText(_translate("CoMPlEx_GUI", "Retr. speed [nm/s]", None))
        self.uploadFvsdBtn.setText(_translate("CoMPlEx_GUI", "Upload All", None))
        self.uploadStartZBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.uploadRetrSpeedBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_24.setText(_translate("CoMPlEx_GUI", "End Z [nm]", None))
        self.label_23.setText(_translate("CoMPlEx_GUI", "Start Z [nm]", None))
        self.uploadAppSpeedBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_22.setText(_translate("CoMPlEx_GUI", "Max Force [pN]", None))
        self.label_27.setText(_translate("CoMPlEx_GUI", "Hold time [s]", None))
        self.uploadHoldTimeBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.constForceCkBox.setText(_translate("CoMPlEx_GUI", "Constant Force", None))
        self.label_25.setText(_translate("CoMPlEx_GUI", "App. speed [nm/s]", None))
        self.uploadEndZBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_28.setText(_translate("CoMPlEx_GUI", "Curves number", None))
        self.uploadMaxFBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.fvsdTab), _translate("CoMPlEx_GUI", "FvsD", None))
        self.removeSegBtn.setText(_translate("CoMPlEx_GUI", "Remove", None))
        self.label_31.setText(_translate("CoMPlEx_GUI", "End Force [pN]", None))
        self.label_30.setText(_translate("CoMPlEx_GUI", "End Z [nm]", None))
        self.label_29.setText(_translate("CoMPlEx_GUI", "Start Z [nm]", None))
        self.label_45.setText(_translate("CoMPlEx_GUI", "Curves number", None))
        self.label_35.setText(_translate("CoMPlEx_GUI", "Hold Time [s]", None))
        self.uploadStartZcBtn.setText(_translate("CoMPlEx_GUI", "Upload", None))
        self.label_46.setText(_translate("CoMPlEx_GUI", "Speed [nm/s]", None))
        self.showZTravelBtn.setText(_translate("CoMPlEx_GUI", "Show Z travel preview", None))
        self.updateSegBtn.setText(_translate("CoMPlEx_GUI", "Update", None))
        self.altZSegBtn.setText(_translate("CoMPlEx_GUI", "Hold Z", None))
        self.altFSegBtn.setText(_translate("CoMPlEx_GUI", "Hold Z", None))
        self.farSegBtn.setText(_translate("CoMPlEx_GUI", "Far", None))
        self.nearSegBtn.setText(_translate("CoMPlEx_GUI", "Near", None))
        self.addSegBtn.setText(_translate("CoMPlEx_GUI", "ADD", None))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.custFvsdTab), _translate("CoMPlEx_GUI", "Custom FvsD", None))
        self.groupBox_2.setTitle(_translate("CoMPlEx_GUI", "Manual movement", None))
        self.label_39.setText(_translate("CoMPlEx_GUI", "X steps number", None))
        self.label_40.setText(_translate("CoMPlEx_GUI", "Y steps number", None))
        self.label_41.setText(_translate("CoMPlEx_GUI", "Z steps number", None))
        self.groupBox.setTitle(_translate("CoMPlEx_GUI", "Map", None))
        self.label_36.setText(_translate("CoMPlEx_GUI", "X steps number", None))
        self.label_37.setText(_translate("CoMPlEx_GUI", "Y steps number", None))
        self.label_38.setText(_translate("CoMPlEx_GUI", "Points number", None))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.motorTab), _translate("CoMPlEx_GUI", "Motors", None))
        self.label_48.setText(_translate("CoMPlEx_GUI", "Directory", None))
        self.label_47.setText(_translate("CoMPlEx_GUI", "File Name root", None))
        self.browseBtn.setText(_translate("CoMPlEx_GUI", "Browse", None))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.saveTab), _translate("CoMPlEx_GUI", "Save", None))
        self.remoteDock.setWindowTitle(_translate("CoMPlEx_GUI", "Remote", None))
        self.channelCmbBox.setItemText(0, _translate("CoMPlEx_GUI", "Engage", None))
        self.channelCmbBox.setItemText(1, _translate("CoMPlEx_GUI", "Calibrate QPD", None))
        self.channelCmbBox.setItemText(2, _translate("CoMPlEx_GUI", "Calibrate K", None))
        self.channelCmbBox.setItemText(3, _translate("CoMPlEx_GUI", "Single Curve", None))
        self.channelCmbBox.setItemText(4, _translate("CoMPlEx_GUI", "Single Custom Curve", None))
        self.channelCmbBox.setItemText(5, _translate("CoMPlEx_GUI", "Curve Map", None))
        self.channelCmbBox.setItemText(6, _translate("CoMPlEx_GUI", "Custom Curve Map", None))
        self.playBtn.setText(_translate("CoMPlEx_GUI", "▶", None))
        self.stopBtn.setText(_translate("CoMPlEx_GUI", "■", None))
        self.action_Set_save_paths.setText(_translate("CoMPlEx_GUI", "&Set save paths", None))
        self.action_QPD_and_piezo.setText(_translate("CoMPlEx_GUI", "&QPD and piezo", None))
        self.action_Motors.setText(_translate("CoMPlEx_GUI", "&Motors", None))
        self.action_General_config.setText(_translate("CoMPlEx_GUI", "&General config", None))
        self.action_Controls_config.setText(_translate("CoMPlEx_GUI", "&Controls config", None))
        self.action_Settings.setText(_translate("CoMPlEx_GUI", "&Settings", None))
        self.action_Remote.setText(_translate("CoMPlEx_GUI", "&Remote", None))
        self.action_Save_parameters.setText(_translate("CoMPlEx_GUI", "&Save parameters", None))
        self.action_Save_parameters.setShortcut(_translate("CoMPlEx_GUI", "Ctrl+S", None))
        self.action_Load_parameters.setText(_translate("CoMPlEx_GUI", "&Load parameters", None))
        self.action_Load_parameters.setShortcut(_translate("CoMPlEx_GUI", "Ctrl+L", None))
        self.action_Exit.setText(_translate("CoMPlEx_GUI", "&Exit", None))
        self.action_Exit.setShortcut(_translate("CoMPlEx_GUI", "Ctrl+Shift+E", None))
        self.action_Edit_config.setText(_translate("CoMPlEx_GUI", "E&dit config", None))
        self.action_Open_SiMPlE.setText(_translate("CoMPlEx_GUI", "&Open SiMPlE", None))

from pyqtgraph import PlotWidget
