# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ettore/GIT/CoMPlEx/GUIs/CoMPlEx_GUI.ui'
#
# Created: Fri Aug 21 17:08:42 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CoMPlEx_GUI(object):
    def setupUi(self, CoMPlEx_GUI):
        CoMPlEx_GUI.setObjectName(_fromUtf8("CoMPlEx_GUI"))
        CoMPlEx_GUI.resize(1072, 748)
        self.centralwidget = QtGui.QWidget(CoMPlEx_GUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        CoMPlEx_GUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(CoMPlEx_GUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1072, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Config = QtGui.QMenu(self.menubar)
        self.menu_Config.setObjectName(_fromUtf8("menu_Config"))
        self.menu_Config_file = QtGui.QMenu(self.menu_Config)
        self.menu_Config_file.setObjectName(_fromUtf8("menu_Config_file"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        CoMPlEx_GUI.setMenuBar(self.menubar)
        self.qpdNpiezoDock = QtGui.QDockWidget(CoMPlEx_GUI)
        self.qpdNpiezoDock.setMaximumSize(QtCore.QSize(524287, 524287))
        self.qpdNpiezoDock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.qpdNpiezoDock.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.qpdNpiezoDock.setObjectName(_fromUtf8("qpdNpiezoDock"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBox_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_2.setDecimals(3)
        self.doubleSpinBox_2.setMinimum(-10.0)
        self.doubleSpinBox_2.setMaximum(10.0)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_2, 1, 1, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox.setDecimals(3)
        self.doubleSpinBox.setMinimum(-10.0)
        self.doubleSpinBox.setMaximum(10.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout_2.addWidget(self.doubleSpinBox, 0, 1, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.dockWidgetContents)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(10)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_2.addWidget(self.progressBar, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBox_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_3.setDecimals(3)
        self.doubleSpinBox_3.setMinimum(0.0)
        self.doubleSpinBox_3.setMaximum(10.0)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_3, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.progressBar_2 = QtGui.QProgressBar(self.dockWidgetContents)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setTextVisible(False)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.gridLayout_2.addWidget(self.progressBar_2, 0, 3, 1, 1)
        self.progressBar_3 = QtGui.QProgressBar(self.dockWidgetContents)
        self.progressBar_3.setMaximum(10)
        self.progressBar_3.setProperty("value", 3)
        self.progressBar_3.setTextVisible(False)
        self.progressBar_3.setInvertedAppearance(True)
        self.progressBar_3.setObjectName(_fromUtf8("progressBar_3"))
        self.gridLayout_2.addWidget(self.progressBar_3, 1, 2, 1, 1)
        self.progressBar_4 = QtGui.QProgressBar(self.dockWidgetContents)
        self.progressBar_4.setMaximum(10)
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setTextVisible(False)
        self.progressBar_4.setObjectName(_fromUtf8("progressBar_4"))
        self.gridLayout_2.addWidget(self.progressBar_4, 1, 3, 1, 1)
        self.progressBar_5 = QtGui.QProgressBar(self.dockWidgetContents)
        self.progressBar_5.setProperty("value", 24)
        self.progressBar_5.setTextVisible(False)
        self.progressBar_5.setObjectName(_fromUtf8("progressBar_5"))
        self.gridLayout_2.addWidget(self.progressBar_5, 2, 2, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.dockWidgetContents)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.doubleSpinBox1 = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBox1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox1.setDecimals(3)
        self.doubleSpinBox1.setMaximum(10.0)
        self.doubleSpinBox1.setObjectName(_fromUtf8("doubleSpinBox1"))
        self.horizontalLayout_2.addWidget(self.doubleSpinBox1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.progressBar_6 = QtGui.QProgressBar(self.dockWidgetContents)
        self.progressBar_6.setProperty("value", 24)
        self.progressBar_6.setTextVisible(False)
        self.progressBar_6.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_6.setObjectName(_fromUtf8("progressBar_6"))
        self.horizontalLayout_3.addWidget(self.progressBar_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.graphicsView_2 = QtGui.QGraphicsView(self.dockWidgetContents)
        self.graphicsView_2.setObjectName(_fromUtf8("graphicsView_2"))
        self.horizontalLayout.addWidget(self.graphicsView_2)
        self.horizontalLayout.setStretch(0, 8)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 3)
        self.qpdNpiezoDock.setWidget(self.dockWidgetContents)
        CoMPlEx_GUI.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.qpdNpiezoDock)
        self.motorsDock = QtGui.QDockWidget(CoMPlEx_GUI)
        self.motorsDock.setMinimumSize(QtCore.QSize(229, 229))
        self.motorsDock.setMaximumSize(QtCore.QSize(229, 229))
        self.motorsDock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.motorsDock.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.motorsDock.setObjectName(_fromUtf8("motorsDock"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.motorTabs = QtGui.QTabWidget(self.dockWidgetContents_2)
        self.motorTabs.setTabPosition(QtGui.QTabWidget.South)
        self.motorTabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.motorTabs.setDocumentMode(True)
        self.motorTabs.setObjectName(_fromUtf8("motorTabs"))
        self.motCtrlTab = QtGui.QWidget()
        self.motCtrlTab.setObjectName(_fromUtf8("motCtrlTab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.motCtrlTab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_4 = QtGui.QPushButton(self.motCtrlTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_4.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_3.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.motCtrlTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_3.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_3.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.motCtrlTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_5.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_3.addWidget(self.pushButton_5, 1, 2, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.motCtrlTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_6.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_3.addWidget(self.pushButton_6, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.motCtrlTab)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 1, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_3)
        self.line = QtGui.QFrame(self.motCtrlTab)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_4.addWidget(self.line)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButton_7 = QtGui.QPushButton(self.motCtrlTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_7.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.label_6 = QtGui.QLabel(self.motCtrlTab)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.pushButton_8 = QtGui.QPushButton(self.motCtrlTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_8.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_8.setAutoDefault(False)
        self.pushButton_8.setDefault(False)
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.verticalLayout_3.addWidget(self.pushButton_8)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4.setStretch(0, 3)
        self.horizontalLayout_4.setStretch(2, 1)
        self.motorTabs.addTab(self.motCtrlTab, _fromUtf8(""))
        self.motSetTab = QtGui.QWidget()
        self.motSetTab.setObjectName(_fromUtf8("motSetTab"))
        self.motorTabs.addTab(self.motSetTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.motorTabs)
        self.motorsDock.setWidget(self.dockWidgetContents_2)
        CoMPlEx_GUI.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.motorsDock)
        self.settingsDock = QtGui.QDockWidget(CoMPlEx_GUI)
        self.settingsDock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.settingsDock.setAllowedAreas(QtCore.Qt.RightDockWidgetArea)
        self.settingsDock.setObjectName(_fromUtf8("settingsDock"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.functionsTabs = QtGui.QTabWidget(self.dockWidgetContents_3)
        self.functionsTabs.setTabsClosable(False)
        self.functionsTabs.setObjectName(_fromUtf8("functionsTabs"))
        self.fbTab = QtGui.QWidget()
        self.fbTab.setObjectName(_fromUtf8("fbTab"))
        self.functionsTabs.addTab(self.fbTab, _fromUtf8(""))
        self.calibQpdTab = QtGui.QWidget()
        self.calibQpdTab.setObjectName(_fromUtf8("calibQpdTab"))
        self.functionsTabs.addTab(self.calibQpdTab, _fromUtf8(""))
        self.calibKTab = QtGui.QWidget()
        self.calibKTab.setObjectName(_fromUtf8("calibKTab"))
        self.functionsTabs.addTab(self.calibKTab, _fromUtf8(""))
        self.fvsdTab = QtGui.QWidget()
        self.fvsdTab.setObjectName(_fromUtf8("fvsdTab"))
        self.functionsTabs.addTab(self.fvsdTab, _fromUtf8(""))
        self.custFvsdTab = QtGui.QWidget()
        self.custFvsdTab.setObjectName(_fromUtf8("custFvsdTab"))
        self.functionsTabs.addTab(self.custFvsdTab, _fromUtf8(""))
        self.mapTab = QtGui.QWidget()
        self.mapTab.setObjectName(_fromUtf8("mapTab"))
        self.functionsTabs.addTab(self.mapTab, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.functionsTabs)
        self.settingsDock.setWidget(self.dockWidgetContents_3)
        CoMPlEx_GUI.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.settingsDock)
        self.remoteDock = QtGui.QDockWidget(CoMPlEx_GUI)
        self.remoteDock.setMinimumSize(QtCore.QSize(207, 118))
        self.remoteDock.setMaximumSize(QtCore.QSize(524287, 118))
        self.remoteDock.setObjectName(_fromUtf8("remoteDock"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.comboBox = QtGui.QComboBox(self.dockWidgetContents_4)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.comboBox)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton_9 = QtGui.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_9.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_5.addWidget(self.pushButton_9)
        self.pushButton_10 = QtGui.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_10.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout_5.addWidget(self.pushButton_10)
        self.progressBar_7 = QtGui.QProgressBar(self.dockWidgetContents_4)
        self.progressBar_7.setProperty("value", 24)
        self.progressBar_7.setObjectName(_fromUtf8("progressBar_7"))
        self.horizontalLayout_5.addWidget(self.progressBar_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.remoteDock.setWidget(self.dockWidgetContents_4)
        CoMPlEx_GUI.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.remoteDock)
        self.action_Set_save_paths = QtGui.QAction(CoMPlEx_GUI)
        self.action_Set_save_paths.setObjectName(_fromUtf8("action_Set_save_paths"))
        self.action_QPD_and_piezo = QtGui.QAction(CoMPlEx_GUI)
        self.action_QPD_and_piezo.setCheckable(True)
        self.action_QPD_and_piezo.setChecked(True)
        self.action_QPD_and_piezo.setObjectName(_fromUtf8("action_QPD_and_piezo"))
        self.action_Motors = QtGui.QAction(CoMPlEx_GUI)
        self.action_Motors.setCheckable(True)
        self.action_Motors.setChecked(True)
        self.action_Motors.setObjectName(_fromUtf8("action_Motors"))
        self.action_General_config = QtGui.QAction(CoMPlEx_GUI)
        self.action_General_config.setObjectName(_fromUtf8("action_General_config"))
        self.action_Controls_config = QtGui.QAction(CoMPlEx_GUI)
        self.action_Controls_config.setObjectName(_fromUtf8("action_Controls_config"))
        self.action_Settings = QtGui.QAction(CoMPlEx_GUI)
        self.action_Settings.setCheckable(True)
        self.action_Settings.setChecked(True)
        self.action_Settings.setObjectName(_fromUtf8("action_Settings"))
        self.action_Remote = QtGui.QAction(CoMPlEx_GUI)
        self.action_Remote.setCheckable(True)
        self.action_Remote.setChecked(True)
        self.action_Remote.setObjectName(_fromUtf8("action_Remote"))
        self.menu_Config_file.addAction(self.action_General_config)
        self.menu_Config_file.addAction(self.action_Controls_config)
        self.menu_Config.addAction(self.menu_Config_file.menuAction())
        self.menu_Config.addAction(self.action_Set_save_paths)
        self.menu_View.addAction(self.action_QPD_and_piezo)
        self.menu_View.addAction(self.action_Motors)
        self.menu_View.addAction(self.action_Settings)
        self.menu_View.addAction(self.action_Remote)
        self.menubar.addAction(self.menu_Config.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())

        self.retranslateUi(CoMPlEx_GUI)
        self.motorTabs.setCurrentIndex(0)
        self.functionsTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CoMPlEx_GUI)

    def retranslateUi(self, CoMPlEx_GUI):
        CoMPlEx_GUI.setWindowTitle(_translate("CoMPlEx_GUI", "MainWindow", None))
        self.menu_Config.setTitle(_translate("CoMPlEx_GUI", "&File", None))
        self.menu_Config_file.setTitle(_translate("CoMPlEx_GUI", "&Config file", None))
        self.menu_View.setTitle(_translate("CoMPlEx_GUI", "&View", None))
        self.qpdNpiezoDock.setWindowTitle(_translate("CoMPlEx_GUI", "QPD and piezo monitor", None))
        self.label_3.setText(_translate("CoMPlEx_GUI", "Sum [V]", None))
        self.label.setText(_translate("CoMPlEx_GUI", "Deflection [V]", None))
        self.label_2.setText(_translate("CoMPlEx_GUI", "Torsion [V]", None))
        self.label_4.setText(_translate("CoMPlEx_GUI", "Z [um]", None))
        self.motorsDock.setWindowTitle(_translate("CoMPlEx_GUI", "Motors", None))
        self.pushButton_4.setText(_translate("CoMPlEx_GUI", "ᐃ", None))
        self.pushButton_3.setText(_translate("CoMPlEx_GUI", "ᐊ", None))
        self.pushButton_5.setText(_translate("CoMPlEx_GUI", "ᐅ", None))
        self.pushButton_6.setText(_translate("CoMPlEx_GUI", "ᐁ", None))
        self.label_5.setText(_translate("CoMPlEx_GUI", "XY", None))
        self.pushButton_7.setText(_translate("CoMPlEx_GUI", "ᐃ", None))
        self.label_6.setText(_translate("CoMPlEx_GUI", "z", None))
        self.pushButton_8.setText(_translate("CoMPlEx_GUI", "ᐁ", None))
        self.motorTabs.setTabText(self.motorTabs.indexOf(self.motCtrlTab), _translate("CoMPlEx_GUI", "Controls", None))
        self.motorTabs.setTabText(self.motorTabs.indexOf(self.motSetTab), _translate("CoMPlEx_GUI", "Settings", None))
        self.settingsDock.setWindowTitle(_translate("CoMPlEx_GUI", "Settings", None))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.fbTab), _translate("CoMPlEx_GUI", "Feedback", None))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.calibQpdTab), _translate("CoMPlEx_GUI", "QPD Calibration", None))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.calibKTab), _translate("CoMPlEx_GUI", "K Calibration", None))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.fvsdTab), _translate("CoMPlEx_GUI", "FvsD", None))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.custFvsdTab), _translate("CoMPlEx_GUI", "Custom FvsD", None))
        self.functionsTabs.setTabText(self.functionsTabs.indexOf(self.mapTab), _translate("CoMPlEx_GUI", "Map", None))
        self.remoteDock.setWindowTitle(_translate("CoMPlEx_GUI", "Remote", None))
        self.comboBox.setItemText(0, _translate("CoMPlEx_GUI", "Engage", None))
        self.comboBox.setItemText(1, _translate("CoMPlEx_GUI", "Calibrate QPD", None))
        self.comboBox.setItemText(2, _translate("CoMPlEx_GUI", "Calibrate K", None))
        self.comboBox.setItemText(3, _translate("CoMPlEx_GUI", "Single Curve", None))
        self.comboBox.setItemText(4, _translate("CoMPlEx_GUI", "Single Custom Curve", None))
        self.comboBox.setItemText(5, _translate("CoMPlEx_GUI", "Curve Map", None))
        self.comboBox.setItemText(6, _translate("CoMPlEx_GUI", "Custom Curve Map", None))
        self.pushButton_9.setText(_translate("CoMPlEx_GUI", "     ▶", None))
        self.pushButton_10.setText(_translate("CoMPlEx_GUI", "■ ", None))
        self.action_Set_save_paths.setText(_translate("CoMPlEx_GUI", "&Set save paths", None))
        self.action_QPD_and_piezo.setText(_translate("CoMPlEx_GUI", "&QPD and piezo", None))
        self.action_Motors.setText(_translate("CoMPlEx_GUI", "&Motors", None))
        self.action_General_config.setText(_translate("CoMPlEx_GUI", "&General config", None))
        self.action_Controls_config.setText(_translate("CoMPlEx_GUI", "&Controls config", None))
        self.action_Settings.setText(_translate("CoMPlEx_GUI", "&Settings", None))
        self.action_Remote.setText(_translate("CoMPlEx_GUI", "&Remote", None))

